# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
NC ?= $(NIOBIUM_CLIENT_DIR)
PY ?= ./.venv/bin/python

# Committed files that a script produces. Every one regenerates byte-identically
# from a fixed seed, so `verify` can compare a fresh run against what is checked
# in. Keep this list in step with what the scripts write.
GENERATED = data/test_records.csv data/feature_bounds.csv \
            model/model.json model/circuit_params.json \
            model/circuit.txt model/model.txt \
            reports/reference_metrics.json reports/sweep.json \
            reports/candidate_validation.json

.PHONY: build clean data model verify

build:
	./run.sh "cmake -S . -B build \
	    -DCMAKE_PREFIX_PATH='$(NC)/vendor/lib/niobium-client;$(NC)/vendor/lib/openfhe' \
	    && cmake --build build -j"

# Rebuild the committed inputs from the public dataset.
data:
	./.venv/bin/python scripts/fetch_data.py
	./.venv/bin/python scripts/build_reference.py

# Re-freeze the design and re-export what the encrypted programs read.
model:
	./.venv/bin/python scripts/gate.py
	./.venv/bin/python scripts/export_model.py

# Regenerate every committed artifact and fail if any differs from what is
# checked in. The committed reports back numbers quoted in docs/ and reports/,
# and regenerating them needs an 18 MB download, so they are tracked rather than
# rebuilt on demand. This target is what keeps them honest: a design change that
# lands without a matching regeneration shows up here instead of silently leaving
# the evidence describing the previous design.
#
# On failure the regenerated files are left in the working tree. Inspect the
# diff, then either commit it or `git checkout -- $(GENERATED)`.
verify:
	@test -f data/raw_encounters.csv || { \
	  echo "verify needs the source dataset. Run 'make data' first."; exit 1; }
	@test -x $(PY) || { \
	  echo "verify needs the project venv at $(PY). See the README Install section."; exit 1; }
	$(PY) scripts/build_reference.py >/dev/null
	$(PY) scripts/sweep.py >/dev/null
	$(PY) scripts/validate_candidates.py >/dev/null
	$(PY) scripts/gate.py >/dev/null
	$(PY) scripts/export_model.py >/dev/null
	@git diff --quiet -- $(GENERATED) || { \
	  echo ""; \
	  echo "verify: committed artifacts do not match a fresh regeneration:"; \
	  git diff --stat -- $(GENERATED); \
	  echo ""; \
	  echo "Commit the regenerated files, or 'git checkout -- $(GENERATED)' to discard."; \
	  exit 1; }
	@echo "verify: all committed artifacts match a fresh regeneration"

# Removes everything a build or a run regenerates. `run_*/` has a trailing
# slash so it matches directories only and cannot delete run_test.sh.
clean:
	rm -rf build/ run_*/ client_home/ server_home/
	rm -rf rescrubbed_server_workload_*/ nbcc_fhetch_replay_source_*/ fhetch_driver_source_*/
	rm -rf demo/client_home/ demo/server_home/
	find . -name __pycache__ -type d -prune -exec rm -rf {} +
	@echo "clean: build tree and run artifacts removed; data/ and model/ kept"
