# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
NC ?= $(NIOBIUM_CLIENT_DIR)

.PHONY: build clean data model

build:
	./run.sh "cmake -S . -B build \
	    -DCMAKE_PREFIX_PATH='$(NC)/vendor/lib/niobium-client;$(NC)/vendor/lib/openfhe' \
	    && cmake --build build -j"

# Rebuild the committed inputs from the public dataset.
data:
	./.venv/bin/python scripts/fetch_data.py
	./.venv/bin/python scripts/build_reference.py

# Re-freeze the design and re-export what the encrypted programs read.
model:
	./.venv/bin/python scripts/gate.py
	./.venv/bin/python scripts/export_model.py

# Removes everything a build or a run regenerates. `run_*/` has a trailing
# slash so it matches directories only and cannot delete run_test.sh.
clean:
	rm -rf build/ run_*/ client_home/ server_home/
	rm -rf readmit_server_workload_*/ nbcc_fhetch_replay_source_*/ fhetch_driver_source_*/
	rm -rf demo/client_home/ demo/server_home/
	find . -name __pycache__ -type d -prune -exec rm -rf {} +
	@echo "clean: build tree and run artifacts removed; data/ and model/ kept"
