#!/usr/bin/env bash
# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
#
# Runs a command in the build-and-run environment. This application was set up
# against a local niobium-client build, so `local` is the default; --container
# runs the same command inside the FHE-dev image instead.
set -euo pipefail

MODE_DEFAULT=local
# Anchored to this script rather than $PWD, so invoking it by absolute path from
# another directory still resolves. Defaults to a checkout inside the repository,
# which is where `git submodule update --init` puts it; export the variable to
# point at one kept elsewhere.
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NIOBIUM_CLIENT_DIR="${NIOBIUM_CLIENT_DIR:-$ROOT_DIR/niobium-client}"

usage() {
    cat <<EOF
Usage: ./run.sh [--container|--local] "<command>"

Active mode for this call: $1

Common invocations:
  ./run.sh "./run_test.sh"             score on the Niobium Fog (default; needs an API key)
  ./run.sh "./run_test.sh --cpu"       local plain-OpenFHE validation
  ./run.sh "./run_test.sh --sim"       local simulator (a rehearsal of the Fog run)
  ./run.sh "./run_test.sh --sim-full"  as --sim, plus a bit-level trace check
  ./run.sh "./run_test.sh --help"      all modes and environment knobs

Build:
  ./run.sh "cmake -S . -B build \\
      -DCMAKE_PREFIX_PATH='\$NIOBIUM_CLIENT_DIR/vendor/lib/niobium-client;\$NIOBIUM_CLIENT_DIR/vendor/lib/openfhe' \\
      && cmake --build build -j"

Modes:
  --local      run on this host against the niobium-client checkout at
               \$NIOBIUM_CLIENT_DIR  (this application's default)
  --container  run inside \$FHE_DEV_IMAGE with this folder mounted at /work
EOF
}

MODE=""; HELP=0
while [ $# -gt 0 ]; do
    case "$1" in
        --container) MODE=container; shift ;;
        --local)     MODE=local;     shift ;;
        -h|--help)   HELP=1;         shift ;;
        *) break ;;
    esac
done
[ -n "$MODE" ] || MODE="$MODE_DEFAULT"
if [ "$HELP" = 1 ] || [ $# -eq 0 ]; then usage "$MODE"; exit 0; fi

if [ "$MODE" = local ]; then
    [ -d "$NIOBIUM_CLIENT_DIR" ] || {
        echo "Local mode needs a built niobium-client. Looked in:" >&2
        echo "  $NIOBIUM_CLIENT_DIR" >&2
        echo "See the Install section of README.md, or use --container." >&2
        exit 1; }
    export NIOBIUM_CLIENT_DIR
    export PATH="$HOME/.local/bin:$PATH"      # fog + nbcc_fhetch_replay live here
    exec bash -c "$*"
fi

command -v docker >/dev/null || {
    echo "Container mode needs Docker. Install it, or use --local." >&2; exit 1; }
IMAGE="${FHE_DEV_IMAGE:-ghcr.io/niobiuminc/fhe-dev:latest}"
FOG=(); [ -d "$HOME/.fog" ] && FOG=(-v "$HOME/.fog:/root/.fog")
ENVFWD=(); for v in RING_DIM RINGCHK RECORD NREC N_ENC FOG_TARGET APP_MODE; do
    [ -n "${!v:-}" ] && ENVFWD+=(-e "$v")
done
exec docker run --rm -v "$PWD":/work -w /work \
    ${FOG[@]+"${FOG[@]}"} ${ENVFWD[@]+"${ENVFWD[@]}"} "$IMAGE" bash -c "$*"
