#!/usr/bin/env bash
# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
#
# keygen -> encrypt -> server -> decrypt, then compare against the faithful twin.
set -euo pipefail

usage() {
  cat <<'EOF'
run_test.sh: encrypted 30-day readmission scoring, end to end.

Usage: ./run_test.sh [--cpu | --sim | --sim-full | -h]
  (no flag)   score on the Niobium Fog (the default; needs an API key)
  --cpu       plain-OpenFHE local validation, the correctness gate
  --sim       record the computation, replay through the local simulator
              (a faithful rehearsal of the Fog run; no account needed)
  --sim-full  as --sim but recording real maths, adding a free bit-level
              check that the recorded trace matches local OpenFHE exactly
              (run --sim and --sim-full together: their answers must agree)

Environment:
  APP_MODE     batch | per_record        (default: batch)
                 batch      = the nightly census: many patients in one request
                 per_record = one patient at discharge
  NREC         patients to score         (default: the whole test set for batch,
                                          1 for per_record)
  RECORD       first test-set row to use (default: 0)
  FOG_TARGET   FOG | FUNC_SIM            (default: FOG)
  RINGCHK      set to --no-ring-dim-check to test a deliberately small ring
               locally. Never applied to a Fog run.
EOF
}

MODE="fog"; FLAG=""; SIMFULL=0
case "${1:-}" in
  --cpu)      MODE="cpu"; FLAG="--cpu";;
  --sim)      MODE="sim"; FLAG="--sim";;
  --sim-full) MODE="sim"; FLAG="--sim"; SIMFULL=1;;
  "")         MODE="fog";;
  -h|--help)  usage; exit 0;;
  *)          usage; exit 2;;
esac

FOG_TARGET="${FOG_TARGET:-FOG}"
RINGCHK="${RINGCHK:-}"
APP_MODE="${APP_MODE:-batch}"
RECORD="${RECORD:-0}"

# Hollow recording on the Fog default and --sim (fast, and what actually
# deploys); real maths on --sim-full so its ring-level check has a baseline.
HOLLOW_FLAG=""
case "$MODE" in
  fog) HOLLOW_FLAG="--hollow";;
  sim) [ "$SIMFULL" = 1 ] || HOLLOW_FLAG="--hollow";;
esac

ROOT="$(cd "$(dirname "$0")" && pwd)"
BUILD="$ROOT/build"
RUN="$ROOT/run_${MODE}"; [ "$SIMFULL" = 1 ] && RUN="$ROOT/run_sim-full"
CLIENT="$RUN/client_home"; SERVER="$RUN/server_home"
# Fail loudly rather than falling back to a Python without the analysis packages:
# a venv whose interpreter symlink has gone stale (the OS package manager moving
# the underlying Python is enough) would otherwise surface as a confusing
# ModuleNotFoundError only after the whole encrypted pipeline had already run.
PY="$ROOT/.venv/bin/python"; [ -x "$PY" ] || PY=python3
if ! "$PY" -c 'import numpy, pandas, sklearn' 2>/dev/null; then
  echo "ERROR: '$PY' cannot import numpy/pandas/scikit-learn, which the results" >&2
  echo "       comparison needs. Recreate the project environment with:" >&2
  echo "         python3 -m venv .venv && ./.venv/bin/pip install \\" >&2
  echo "             numpy pandas scikit-learn ucimlrepo certifi" >&2
  exit 1
fi

# The deployment's unit of work: one whole batch, or one patient.
if [ "$APP_MODE" = "per_record" ]; then
  NREC="${NREC:-1}"
else
  NREC="${NREC:-$(( $(wc -l < "$ROOT/data/test_records.csv") - 1 ))}"
fi

rm -rf "$RUN" "$ROOT"/readmit_server_workload_* "$ROOT"/nbcc_fhetch_replay_source_*
mkdir -p "$CLIENT" "$SERVER"

echo "=============================================================================="
echo " Encrypted 30-day readmission scoring: $MODE run"
echo " request shape: $APP_MODE     patients: $NREC     first row: $RECORD"
echo "=============================================================================="

# ── 1. keygen: ALL keys land in the client home ──────────────────────────────
# The client gets circuit.txt (public parameters) and never model.txt: it has no
# need for the vendor's weights, and the loader refuses that file if handed it.
cp "$ROOT/model/circuit.txt" "$CLIENT/"
T0=$(date +%s.%N)
"$BUILD/readmit_keygen" "$CLIENT" "$APP_MODE"
T_KEYGEN=$($PY -c "print(f'{$(date +%s.%N)-$T0:.2f}')")

# ── 2. provision the server home: context, public + eval keys, model.
#      No secret key. No patient data. Safe to copy to untrusted infrastructure.
cp "$CLIENT/cc.bin" "$CLIENT/pk.bin" "$CLIENT/mk.bin" "$CLIENT/rk.bin" "$SERVER/"
cp "$ROOT/model/model.txt" "$ROOT/model/circuit.txt" "$SERVER/"
[ ! -f "$SERVER/sk.bin" ] || { echo "[FATAL] secret key in server home"; exit 1; }
[ ! -f "$CLIENT/model.txt" ] || { echo "[FATAL] weights present in client home"; exit 1; }

# ── 3. negative test: the server must refuse to run with a secret key present ──
# Assert on the guard's OWN exit code (2), not merely on a non-zero status. At
# this point the server home has no input ciphertexts either, so any-nonzero
# would pass even if the guard had been removed entirely.
cp "$CLIENT/sk.bin" "$SERVER/sk.bin"
printf 'mode %s\nn_records 1\n' "$APP_MODE" > "$SERVER/meta.txt"
set +e
NEG_OUT=$("$BUILD/readmit_server" "$SERVER" $FLAG $RINGCHK 2>&1); NEG_RC=$?
set -e
rm -f "$SERVER/sk.bin"
if [ "$NEG_RC" -ne 2 ]; then
  echo "[FATAL] expected the secret-key guard (exit 2), got exit $NEG_RC:"
  echo "$NEG_OUT" | head -5
  exit 1
fi
case "$NEG_OUT" in
  *"secret key is present"*) ;;
  *) echo "[FATAL] exit 2 but not from the secret-key guard:"; echo "$NEG_OUT" | head -5; exit 1;;
esac
echo "negative test: server refused a planted secret key (exit 2, guard message)  [OK]"

# ── 4. Fog mode: preflight for an API key ────────────────────────────────────
if [ "$MODE" = "fog" ] && [ ! -f "$HOME/.fog/credentials" ] && [ -z "${FOG_API_TOKEN:-}" ]; then
  echo
  echo "This program runs on the Niobium Fog and needs an API key, but none was found."
  echo "  • Sign in:  fog login                                   (mints a key from your account)"
  echo "  • Sign up:  https://console.niobium.co/request-account"
  echo "  • No account yet? Validate locally instead:   ./run_test.sh --sim"
  # Exit non-zero, with a code distinct from a fidelity failure (1). The bare
  # invocation is the documented default and this script's exit status is the
  # pass/fail signal, so returning 0 would let an unconfigured CI record a green
  # run in which nothing was encrypted, computed or compared.
  exit 4
fi

# ── 5. encrypt -> server -> decrypt ──────────────────────────────────────────
T0=$(date +%s.%N)
"$BUILD/readmit_encrypt" "$CLIENT" "$ROOT/data/test_records.csv" \
    "$ROOT/data/feature_bounds.csv" --mode "$APP_MODE" --n "$NREC" --offset "$RECORD"
T_ENC=$($PY -c "print(f'{$(date +%s.%N)-$T0:.2f}')")

cp "$CLIENT"/ct_x*.bin "$SERVER/"              # only ciphertext crosses the boundary
cp "$CLIENT/meta.txt" "$SERVER/"

T0=$(date +%s.%N)
if [ "$MODE" = "fog" ]; then
  # The ring-dimension guard is never bypassed on a Fog dispatch.
  fog submit "$BUILD/readmit_server" "$SERVER" $HOLLOW_FLAG --target="$FOG_TARGET"
  PEAK_RSS="n/a (ran on the Fog)"
else
  $PY "$ROOT/scripts/run_with_rss.py" "$RUN/rss.txt" \
      "$BUILD/readmit_server" "$SERVER" $FLAG $HOLLOW_FLAG $RINGCHK
  PEAK_RSS=$(cat "$RUN/rss.txt")
fi
T_SRV=$($PY -c "print(f'{$(date +%s.%N)-$T0:.2f}')")

cp "$SERVER/ct_result.bin" "$CLIENT/"
T0=$(date +%s.%N)
# --raw is for THIS harness only: the fidelity comparison needs the pre-rounding
# value to measure encryption error. A deployed client never passes it, because
# that value is invertible back to the risk score.
"$BUILD/readmit_decrypt" "$CLIENT" --raw > "$RUN/decrypted.csv"
T_DEC=$($PY -c "print(f'{$(date +%s.%N)-$T0:.2f}')")

# ── 6. report ────────────────────────────────────────────────────────────────
CT_IN=$(cat "$CLIENT"/ct_x*.bin | wc -c | tr -d ' ')
CT_OUT=$(wc -c < "$CLIENT/ct_result.bin" | tr -d ' ')
KEYS=$(cat "$SERVER/cc.bin" "$SERVER/pk.bin" "$SERVER/mk.bin" "$SERVER/rk.bin" | wc -c | tr -d ' ')

exec $PY "$ROOT/scripts/compare.py" \
    --decrypted "$RUN/decrypted.csv" \
    --mode "$APP_MODE" --offset "$RECORD" --n "$NREC" \
    --run-mode "$MODE$([ "$SIMFULL" = 1 ] && echo '-full' || true)" \
    --t-keygen "$T_KEYGEN" --t-encrypt "$T_ENC" --t-server "$T_SRV" --t-decrypt "$T_DEC" \
    --bytes-in "$CT_IN" --bytes-out "$CT_OUT" --bytes-keys "$KEYS" \
    --peak-rss "$PEAK_RSS"
