// Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
//
// decrypt: runs on the HOSPITAL. Recovers the risk bands.
//
// This is the only program that holds the decryption key. It applies the
// reference model's exact decision rule: round the returned value to the
// nearest of {0 = low, 1 = moderate, 2 = high}.
//
// It deliberately prints ONLY the band. The pre-rounding value is a smooth,
// invertible function of the patient's risk score, so printing it would hand
// back the very number the banding design exists to withhold. About 29 crafted
// queries would then recover the vendor's whole model. --raw exposes it for the
// validation harness, which needs it to measure encryption error, and must not
// be used on a deployed client.
//
// Validation against the twin lives in run_test.sh, not here, so the deployed
// binary carries no test-only inputs.
//
//   readmit_decrypt <home> [result.bin] [--raw]
//
// Prints CSV to stdout: index,band,band_name  (plus `value` under --raw)

#include "readmit.hpp"

#include <cmath>
#include <iomanip>
#include <iostream>

namespace fs = std::filesystem;

int main(int argc, char* argv[]) try {
    std::string home_s, result_s;
    bool raw = false;
    for (int i = 1; i < argc; ++i) {
        std::string a = argv[i];
        if      (a == "--raw") raw = true;
        else if (a == "-h" || a == "--help") {
            std::cerr << "Usage: " << argv[0] << " <home> [result.bin] [--raw]\n";
            return 0;
        }
        else if (home_s.empty())   home_s = a;
        else if (result_s.empty()) result_s = a;
        else { std::cerr << "Unknown arg: " << a << "\n"; return 1; }
    }
    if (home_s.empty()) {
        std::cerr << "Usage: " << argv[0] << " <home> [result.bin] [--raw]\n";
        return 1;
    }
    const fs::path home = home_s;
    const fs::path result_path =
        result_s.empty() ? home / readmit::files::kResult : fs::path(result_s);

    const auto params = readmit::LoadPublicParams(home / readmit::files::kCircuit);
    auto cc = readmit::LoadContextWithEvalKeys(home);
    auto sk = readmit::LoadSecretKey(home, cc);
    const auto meta = readmit::LoadMeta(home);

    Ciphertext<DCRTPoly> ct;
    if (!Serial::DeserializeFromFile(result_path.string(), ct, SerType::BINARY))
        throw std::runtime_error("cannot load " + result_path.string());

    Plaintext pt;
    cc->Decrypt(sk, ct, &pt);

    // In batch mode each patient occupies one slot; in per-record mode the
    // rotate-and-sum leaves the answer in slot 0.
    const int n = (meta.mode == readmit::Mode::Batch) ? meta.n_records : 1;
    pt->SetLength(size_t(n));
    const auto& v = pt->GetRealPackedValue();

    static const char* kBandName[] = {"low", "moderate", "high"};

    std::cout << (raw ? "index,value,band,band_name\n" : "index,band,band_name\n");

    // Plausibility check. A healthy value lies inside the range the band
    // polynomial can produce; a run that lost its level budget, hit a key
    // mismatch, or evaluated out of domain comes back wildly outside it, and
    // rounding that into a band would make a broken run indistinguishable from
    // a good one.
    //
    // A "close to a whole number" test would flag most of a real batch: patients
    // near a band threshold decrypt to fractional values, because the staircase
    // the circuit evaluates is smooth.
    const double margin = 0.05;
    const double lo_ok = params.band_value_min - margin;
    const double hi_ok = params.band_value_max + margin;
    int suspect = 0;
    double worst_excursion = 0.0;

    for (int i = 0; i < n; ++i) {
        const double val = v[size_t(i)];
        const double excursion = std::max(lo_ok - val, val - hi_ok);
        if (excursion > worst_excursion) worst_excursion = excursion;
        if (!std::isfinite(val) || excursion > 0.0) ++suspect;

        long b = std::lround(val);
        if (b < 0) b = 0;
        if (b > 2) b = 2;

        std::cout << i << ',';
        if (raw) std::cout << std::setprecision(10) << val << ',';
        std::cout << b << ',' << kBandName[b] << '\n';
    }

    if (suspect > 0) {
        std::cerr << "[decrypt] REFUSING TO CERTIFY: " << suspect << " of " << n
                  << " results fall outside the range this circuit can produce ["
                  << lo_ok << ", " << hi_ok << "]; worst excursion "
                  << worst_excursion << ".\n"
                  << "[decrypt] The computation did not return intact; these bands"
                     " must not be used clinically.\n";
        return 3;
    }
    std::cerr << "[decrypt] " << n << " band(s) recovered, all within the range "
                 "this circuit can produce [" << lo_ok << ", " << hi_ok << "]\n";
    return 0;
} catch (const std::exception& e) {
    std::cerr << "[decrypt] error: " << e.what() << "\n";
    return 1;
}
