// Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
//
// encrypt: runs on the HOSPITAL. Turns patient records into ciphertext.
//
// This program is where the published input box is ENFORCED. Each field is
// clipped to its declared clinical range and mapped to [0,1] before encryption.
// That is not cosmetic: it is what guarantees the vendor's band polynomial is
// never evaluated outside the interval it was fitted to, which in a batched run
// would otherwise fail to decrypt for EVERY patient, not just the offending one.
//
// A bounds file that no program reads is not enforcement, so the check lives
// here on the client path rather than in the server's circuit.
//
//   readmit_encrypt <home> <records.csv> <bounds.csv> [--mode batch|per_record]
//                   [--n <count>] [--offset <row>]

#include "readmit.hpp"

#include <chrono>
#include <fstream>
#include <iostream>
#include <sstream>

namespace fs = std::filesystem;

namespace {

struct Records {
    std::vector<std::string> header;
    std::vector<std::vector<double>> rows;   // raw, pre-clip field values
};

// Reads the feature columns named by `want`, in that order, ignoring any extra
// columns (such as the outcome label carried alongside for scoring).
Records ReadRecords(const fs::path& csv, const std::vector<std::string>& want,
                    size_t offset, size_t limit) {
    std::ifstream in(csv);
    if (!in) throw std::runtime_error("cannot open " + csv.string());

    std::string line;
    if (!std::getline(in, line)) throw std::runtime_error("empty file " + csv.string());

    std::vector<std::string> cols;
    {
        std::istringstream ls(line);
        std::string c;
        while (std::getline(ls, c, ',')) cols.push_back(c);
    }
    std::vector<int> pick;
    for (const auto& name : want) {
        int at = -1;
        for (size_t i = 0; i < cols.size(); ++i) if (cols[i] == name) { at = int(i); break; }
        if (at < 0) throw std::runtime_error("column '" + name + "' missing from " + csv.string());
        pick.push_back(at);
    }

    Records r;
    r.header = want;
    size_t row = 0;
    while (std::getline(in, line) && r.rows.size() < limit) {
        if (line.empty()) continue;
        if (row++ < offset) continue;
        std::vector<std::string> cell;
        std::istringstream ls(line);
        std::string c;
        while (std::getline(ls, c, ',')) cell.push_back(c);
        std::vector<double> v;
        v.reserve(pick.size());
        for (int at : pick) v.push_back(std::stod(cell.at(size_t(at))));
        r.rows.push_back(std::move(v));
    }
    if (r.rows.empty()) throw std::runtime_error("no records read from " + csv.string());
    return r;
}

}  // namespace

int main(int argc, char* argv[]) try {
    if (argc < 4) {
        std::cerr << "Usage: " << argv[0]
                  << " <home> <records.csv> <bounds.csv>"
                     " [--mode batch|per_record] [--n <count>] [--offset <row>]\n";
        return 1;
    }
    const fs::path home = argv[1], records_csv = argv[2], bounds_csv = argv[3];
    readmit::Mode mode = readmit::Mode::Batch;
    size_t want_n = 0, offset = 0;
    for (int i = 4; i < argc; ++i) {
        std::string a = argv[i];
        if      (a == "--mode"   && i + 1 < argc) mode   = readmit::ParseMode(argv[++i]);
        else if (a == "--n"      && i + 1 < argc) want_n = std::stoul(argv[++i]);
        else if (a == "--offset" && i + 1 < argc) offset = std::stoul(argv[++i]);
        else { std::cerr << "Unknown arg: " << a << "\n"; return 1; }
    }

    // Public parameters only. Packing needs the field order and the slot
    // stride, not the weights.
    const auto p = readmit::LoadPublicParams(home / readmit::files::kCircuit);

    auto cc = readmit::LoadContextWithEvalKeys(home);
    auto pk = readmit::LoadPublicKey(home, cc);
    const size_t slots = cc->GetEncodingParams()->GetBatchSize();

    const auto bounds = readmit::LoadBounds(bounds_csv);
    if (static_cast<int>(bounds.names.size()) != p.n_features)
        throw std::runtime_error("bounds file declares " +
                                 std::to_string(bounds.names.size()) +
                                 " features, circuit expects " +
                                 std::to_string(p.n_features));
    // Check the NAMES, not just the count. Slot j of the encrypted column is
    // multiplied by weight j on the server, so a reordered or edited bounds file
    // would pair every field with the wrong weight and the wrong clip range,
    // producing confidently wrong bands with no error raised anywhere.
    for (int j = 0; j < p.n_features; ++j) {
        if (bounds.names[size_t(j)] != p.feature_names[size_t(j)])
            throw std::runtime_error(
                "field order mismatch at position " + std::to_string(j) + ": "
                + bounds_csv.string() + " has '" + bounds.names[size_t(j)]
                + "' where the circuit expects '" + p.feature_names[size_t(j)]
                + "'. Every field would be scored against the wrong weight.");
    }

    const size_t cap = (mode == readmit::Mode::PerRecord) ? 1 : slots;
    if (want_n == 0) want_n = cap;
    if (want_n > cap)
        throw std::runtime_error("requested " + std::to_string(want_n) +
                                 " records but this mode holds at most " +
                                 std::to_string(cap));

    const auto rec = ReadRecords(records_csv, bounds.names, offset, want_n);
    const size_t n = rec.rows.size();

    // ── enforce the published box ─────────────────────────────────────────
    // Clip, don't reject: every patient is admitted, so a batch can never be
    // spoiled by one extreme record. Count how many values saturated so the
    // effect is reported rather than silent.
    size_t clipped_values = 0, clipped_rows = 0;
    std::vector<std::vector<double>> X(n, std::vector<double>(p.n_features));
    for (size_t i = 0; i < n; ++i) {
        bool any = false;
        for (int j = 0; j < p.n_features; ++j) {
            const double raw = rec.rows[i][size_t(j)];
            if (raw < bounds.lo[size_t(j)] || raw > bounds.hi[size_t(j)]) {
                ++clipped_values;
                any = true;
            }
            X[i][size_t(j)] = readmit::ClipScale(raw, bounds.lo[size_t(j)],
                                                 bounds.hi[size_t(j)]);
        }
        if (any) ++clipped_rows;
    }

    const auto t0 = std::chrono::steady_clock::now();
    size_t bytes = 0;

    if (mode == readmit::Mode::Batch) {
        // Column-major: ciphertext j holds field j for every patient, one per
        // slot. The vendor's weight for that field then multiplies the whole
        // column at once, which is how 32,768 patients cost about what one does.
        for (int j = 0; j < p.n_features; ++j) {
            std::vector<double> col(n);
            for (size_t i = 0; i < n; ++i) col[i] = X[i][size_t(j)];
            auto ct = cc->Encrypt(pk, cc->MakeCKKSPackedPlaintext(col));
            const auto out = home / readmit::InputFile(mode, j);
            if (!Serial::SerializeToFile(out.string(), ct, SerType::BINARY))
                throw std::runtime_error("failed to write " + out.string());
            bytes += fs::file_size(out);
        }
    } else {
        // One patient's fields laid out across the slots of a single ciphertext,
        // so an interactive query costs one ciphertext rather than one per field.
        std::vector<double> v(size_t(p.feature_slot_stride), 0.0);
        for (int j = 0; j < p.n_features; ++j) v[size_t(j)] = X[0][size_t(j)];
        auto ct = cc->Encrypt(pk, cc->MakeCKKSPackedPlaintext(v));
        const auto out = home / readmit::InputFile(mode, 0);
        if (!Serial::SerializeToFile(out.string(), ct, SerType::BINARY))
            throw std::runtime_error("failed to write " + out.string());
        bytes += fs::file_size(out);
    }

    readmit::SaveMeta(home, {mode, int(n)});

    const double secs = std::chrono::duration<double>(
        std::chrono::steady_clock::now() - t0).count();
    std::cout << "[encrypt] mode=" << readmit::ModeName(mode)
              << " patients=" << n
              << " ciphertexts=" << (mode == readmit::Mode::Batch ? p.n_features : 1)
              << " bytes=" << bytes
              << " (" << bytes / 1048576.0 << " MiB, " << secs << "s)\n";
    std::cout << "[encrypt] input box: " << clipped_values << " field value(s) across "
              << clipped_rows << " patient(s) saturated at a published bound; "
              << "0 patients rejected\n";
    return 0;
} catch (const std::exception& e) {
    std::cerr << "[encrypt] error: " << e.what() << "\n";
    return 1;
}
