// Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
//
// readmit.cpp: shared implementation. context, key I/O, the model file, and
// the one copy of the homomorphic circuit.

#include "readmit.hpp"

#include <fstream>
#include <iostream>
#include <sstream>
#include <stdexcept>

namespace fs = std::filesystem;

namespace readmit {

const char* ModeName(Mode m) {
    return m == Mode::Batch ? "batch" : "per_record";
}

Mode ParseMode(const std::string& s) {
    if (s == "batch") return Mode::Batch;
    if (s == "per_record" || s == "per-record") return Mode::PerRecord;
    throw std::runtime_error("unknown mode '" + s + "' (want batch | per_record)");
}

// ── public circuit parameters (client side) ───────────────────────────────
// Fields only the vendor may hold. Seeing any of these in a file a CLIENT
// program opened means the wrong file was provisioned, so refuse it loudly
// instead of quietly disclosing the model.
static bool IsServerOnlyKey(const std::string& key) {
    return key == "weights" || key == "bias" || key == "threshold_moderate"
        || key == "threshold_high" || key == "steepness" || key == "degree"
        || key == "domain_lo" || key == "domain_hi";
}

PublicParams LoadPublicParams(const fs::path& file) {
    std::ifstream in(file);
    if (!in) throw std::runtime_error("cannot open circuit parameters " + file.string());

    PublicParams p;
    std::string line;
    while (std::getline(in, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::istringstream ls(line);
        std::string key;
        ls >> key;

        if (IsServerOnlyKey(key))
            throw std::runtime_error(
                "refusing to read '" + file.string() + "': it contains the "
                "server-only field '" + key + "'. Client programs must be given "
                "circuit.txt (public parameters), never model.txt (the weights).");

        if      (key == "n_features")          ls >> p.n_features;
        else if (key == "feature_slot_stride") ls >> p.feature_slot_stride;
        else if (key == "ring_dim")            ls >> p.ring_dim;
        else if (key == "mult_depth")          ls >> p.mult_depth;
        else if (key == "scaling_mod_size")    ls >> p.scaling_mod_size;
        else if (key == "first_mod_size")      ls >> p.first_mod_size;
        else if (key == "noise_tolerance")     ls >> p.noise_tolerance;
        else if (key == "band_value_min")      ls >> p.band_value_min;
        else if (key == "band_value_max")      ls >> p.band_value_max;
        else if (key == "feature_names") {
            std::string n;
            while (ls >> n) p.feature_names.push_back(n);
        }
    }
    if (p.n_features <= 0 || p.feature_slot_stride < p.n_features)
        throw std::runtime_error("malformed circuit parameters " + file.string());
    if (static_cast<int>(p.feature_names.size()) != p.n_features)
        throw std::runtime_error(
            file.string() + " lists " + std::to_string(p.feature_names.size())
            + " feature names but declares " + std::to_string(p.n_features)
            + " features");
    if (!(p.noise_tolerance > 0.0))
        throw std::runtime_error(file.string() + " has no usable noise_tolerance");
    return p;
}

// ── model file ────────────────────────────────────────────────────────────
Model LoadModel(const fs::path& file) {
    std::ifstream in(file);
    if (!in) throw std::runtime_error("cannot open model file " + file.string());

    Model m;
    bool saw_weights = false;
    std::string line;
    while (std::getline(in, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::istringstream ls(line);
        std::string key;
        ls >> key;
        if      (key == "n_features")          ls >> m.n_features;
        else if (key == "bias")                ls >> m.bias;
        else if (key == "threshold_moderate")  ls >> m.threshold_moderate;
        else if (key == "threshold_high")      ls >> m.threshold_high;
        else if (key == "steepness")           ls >> m.steepness;
        else if (key == "degree")              ls >> m.degree;
        else if (key == "domain_lo")           ls >> m.domain_lo;
        else if (key == "domain_hi")           ls >> m.domain_hi;
        else if (key == "ring_dim")            ls >> m.ring_dim;
        else if (key == "mult_depth")          ls >> m.mult_depth;
        else if (key == "scaling_mod_size")    ls >> m.scaling_mod_size;
        else if (key == "first_mod_size")      ls >> m.first_mod_size;
        else if (key == "feature_slot_stride") ls >> m.feature_slot_stride;
        else if (key == "weights") {
            double w;
            while (ls >> w) m.weights.push_back(w);
            saw_weights = true;
        }
    }
    if (!saw_weights || m.n_features <= 0)
        throw std::runtime_error("malformed model file " + file.string());
    if (static_cast<int>(m.weights.size()) != m.n_features)
        throw std::runtime_error("model has " + std::to_string(m.weights.size()) +
                                 " weights but declares " +
                                 std::to_string(m.n_features) + " features");
    if (m.feature_slot_stride < m.n_features)
        throw std::runtime_error("feature_slot_stride is smaller than n_features");
    return m;
}

// ── context ───────────────────────────────────────────────────────────────
CryptoContext<DCRTPoly> BuildContext(usint ring_dim, usint mult_depth,
                                     usint scaling_mod_size, usint first_mod_size) {
    CCParams<CryptoContextCKKSRNS> p;
    p.SetMultiplicativeDepth(mult_depth);
    p.SetScalingModSize(scaling_mod_size);
    p.SetFirstModSize(first_mod_size);
    // Set the ring explicitly. Left to be inferred from the slot count it can
    // land below the security floor, which fails key generation only after the
    // build has been paid for.
    p.SetRingDim(ring_dim);
    p.SetSecurityLevel(HEStd_128_classic);
    p.SetScalingTechnique(FLEXIBLEAUTO);
    p.SetBatchSize(ring_dim / 2);

    auto cc = GenCryptoContext(p);
    cc->Enable(PKE);
    cc->Enable(KEYSWITCH);
    cc->Enable(LEVELEDSHE);
    cc->Enable(ADVANCEDSHE);   // needed for EvalChebyshevFunction
    return cc;
}

std::vector<int32_t> RotationIndices(int feature_slot_stride) {
    std::vector<int32_t> idx;
    for (int32_t r = 1; r < feature_slot_stride; r <<= 1) idx.push_back(r);
    return idx;
}

// ── key I/O ───────────────────────────────────────────────────────────────
static void MustSerialize(bool ok, const std::string& what) {
    if (!ok) throw std::runtime_error("failed to write " + what);
}

void SaveContextAndKeys(const fs::path& home, const CryptoContext<DCRTPoly>& cc,
                        const KeyPair<DCRTPoly>& kp) {
    fs::create_directories(home);
    MustSerialize(Serial::SerializeToFile((home / files::kContext).string(), cc,
                                          SerType::BINARY), files::kContext);
    MustSerialize(Serial::SerializeToFile((home / files::kPublicKey).string(),
                                          kp.publicKey, SerType::BINARY),
                  files::kPublicKey);
    MustSerialize(Serial::SerializeToFile((home / files::kSecretKey).string(),
                                          kp.secretKey, SerType::BINARY),
                  files::kSecretKey);

    std::ofstream mk((home / files::kMultKey).string(), std::ios::binary);
    MustSerialize(cc->SerializeEvalMultKey(mk, SerType::BINARY), files::kMultKey);
    mk.close();

    // Written even when empty, so provisioning is uniform across modes.
    std::ofstream rk((home / files::kRotKey).string(), std::ios::binary);
    cc->SerializeEvalAutomorphismKey(rk, SerType::BINARY);
    rk.close();
}

CryptoContext<DCRTPoly> LoadContextWithEvalKeys(const fs::path& home) {
    CryptoContext<DCRTPoly> cc;
    if (!Serial::DeserializeFromFile((home / files::kContext).string(), cc,
                                     SerType::BINARY))
        throw std::runtime_error("cannot load " + (home / files::kContext).string());

    // Report a missing or unreadable evaluation key HERE. Letting it slide means
    // the process starts, prints a healthy-looking request summary, and then
    // dies deep inside EvalMult/EvalRotate with an opaque "EvalKey for index [1]
    // is not found", a much harder failure to diagnose than a named one.
    std::ifstream mk((home / files::kMultKey).string(), std::ios::binary);
    if (!mk)
        throw std::runtime_error("missing " + (home / files::kMultKey).string()
                                 + " (the relinearisation key)");
    if (!cc->DeserializeEvalMultKey(mk, SerType::BINARY))
        throw std::runtime_error("could not read " + (home / files::kMultKey).string());

    // rk.bin is written even when empty (batch mode needs no rotations), so an
    // empty automorphism map is legitimate; an unreadable file is not.
    std::ifstream rk((home / files::kRotKey).string(), std::ios::binary);
    if (!rk)
        throw std::runtime_error("missing " + (home / files::kRotKey).string()
                                 + " (the rotation key file)");
    if (rk.peek() != std::ifstream::traits_type::eof()
        && !cc->DeserializeEvalAutomorphismKey(rk, SerType::BINARY))
        throw std::runtime_error("could not read " + (home / files::kRotKey).string());
    return cc;
}

PublicKey<DCRTPoly> LoadPublicKey(const fs::path& home,
                                  const CryptoContext<DCRTPoly>&) {
    PublicKey<DCRTPoly> pk;
    if (!Serial::DeserializeFromFile((home / files::kPublicKey).string(), pk,
                                     SerType::BINARY))
        throw std::runtime_error("cannot load " + (home / files::kPublicKey).string());
    return pk;
}

PrivateKey<DCRTPoly> LoadSecretKey(const fs::path& home,
                                   const CryptoContext<DCRTPoly>&) {
    PrivateKey<DCRTPoly> sk;
    if (!Serial::DeserializeFromFile((home / files::kSecretKey).string(), sk,
                                     SerType::BINARY))
        throw std::runtime_error("cannot load " + (home / files::kSecretKey).string());
    return sk;
}

// ── the published input box ───────────────────────────────────────────────
Bounds LoadBounds(const fs::path& csv) {
    std::ifstream in(csv);
    if (!in) throw std::runtime_error("cannot open bounds file " + csv.string());
    Bounds b;
    std::string line;
    std::getline(in, line);                      // header: feature,lo,hi
    while (std::getline(in, line)) {
        if (line.empty()) continue;
        std::istringstream ls(line);
        std::string name, lo_s, hi_s;
        std::getline(ls, name, ',');
        std::getline(ls, lo_s, ',');
        std::getline(ls, hi_s, ',');
        if (name.empty() || lo_s.empty() || hi_s.empty())
            throw std::runtime_error("malformed row in " + csv.string() + ": " + line);

        const double lo = std::stod(lo_s), hi = std::stod(hi_s);
        // A degenerate or non-finite range makes ClipScale divide by zero. The
        // resulting NaN would not spoil one patient's answer: CKKS encoding is a
        // transform across all slots, so a single NaN corrupts the entire batch.
        if (!std::isfinite(lo) || !std::isfinite(hi) || !(hi > lo))
            throw std::runtime_error(
                "bad range for '" + name + "' in " + csv.string() + ": need a "
                "finite lo < hi, got [" + lo_s + ", " + hi_s + "]");

        b.names.push_back(name);
        b.lo.push_back(lo);
        b.hi.push_back(hi);
    }
    if (b.names.empty()) throw std::runtime_error("no rows in " + csv.string());
    return b;
}

// ── plaintext operands ────────────────────────────────────────────────────
CircuitPlaintexts MakePlaintexts(const CryptoContext<DCRTPoly>& cc,
                                 const Model& m, Mode mode, size_t slots) {
    CircuitPlaintexts pt;

    if (mode == Mode::Batch) {
        // One plaintext per field, holding that field's weight in every slot,
        // because every slot of that ciphertext is a different patient's value
        // for the same field.
        pt.weight_cols.reserve(m.n_features);
        for (int j = 0; j < m.n_features; ++j) {
            std::vector<double> col(slots, m.weights[j]);
            pt.weight_cols.push_back(cc->MakeCKKSPackedPlaintext(col));
        }
    } else {
        // One plaintext holding the weights across slots, matching the layout
        // the client used for a single patient's fields.
        std::vector<double> w(slots, 0.0);
        for (int j = 0; j < m.n_features; ++j) w[j] = m.weights[j];
        pt.weights_packed = cc->MakeCKKSPackedPlaintext(w);
    }

    std::vector<double> bias(slots, m.bias);
    pt.bias_all = cc->MakeCKKSPackedPlaintext(bias);
    return pt;
}

// ── THE CIRCUIT ───────────────────────────────────────────────────────────
Ciphertext<DCRTPoly> run_circuit(const CryptoContext<DCRTPoly>& cc,
                                 const Model& m, Mode mode,
                                 const std::vector<Ciphertext<DCRTPoly>>& in,
                                 CircuitPlaintexts& pt) {
    Ciphertext<DCRTPoly> score;

    if (mode == Mode::Batch) {
        if (static_cast<int>(in.size()) != m.n_features)
            throw std::runtime_error("batch mode expects one ciphertext per field");

        // Weighted tally across ciphertexts. Each product is ciphertext x
        // plaintext, which is cheap and costs a single level for the whole
        // layer; the additions are free. No rotations, hence no rotation keys.
        std::vector<Ciphertext<DCRTPoly>> terms;
        terms.reserve(m.n_features);
        for (int j = 0; j < m.n_features; ++j)
            terms.push_back(cc->EvalMult(in[j], pt.weight_cols[j]));

        // Tree-structured reduction rather than a running total: same result,
        // shallower accumulation of rounding.
        score = cc->EvalAddMany(terms);
    } else {
        if (in.size() != 1)
            throw std::runtime_error("per-record mode expects one ciphertext");

        score = cc->EvalMult(in[0], pt.weights_packed);

        // Fold the per-field products together: rotate by 1, 2, 4, ... and add.
        // Free in multiplicative depth; needs one rotation key per step.
        for (int32_t r = 1; r < m.feature_slot_stride; r <<= 1)
            score = cc->EvalAdd(score, cc->EvalRotate(score, r));
    }

    score = cc->EvalAdd(score, pt.bias_all);

    // The band. One polynomial over the whole two-step staircase, at the same depth as
    // approximating each threshold separately would cost, half the work, and a
    // single output ciphertext.
    return cc->EvalChebyshevFunction(
        [&m](double x) { return BandStaircase(x, m); },
        score, m.domain_lo, m.domain_hi, m.degree);
}

// ── request files and metadata ────────────────────────────────────────────
std::string InputFile(Mode mode, int j) {
    if (mode == Mode::PerRecord) return "ct_x.bin";
    return "ct_x_f" + std::to_string(j) + ".bin";
}

void SaveMeta(const fs::path& home, const Meta& meta) {
    std::ofstream out((home / files::kMeta).string());
    out << "mode " << ModeName(meta.mode) << "\n"
        << "n_records " << meta.n_records << "\n";
}

Meta LoadMeta(const fs::path& home) {
    std::ifstream in((home / files::kMeta).string());
    if (!in) throw std::runtime_error("cannot open " + (home / files::kMeta).string());
    Meta meta;
    std::string key, val;
    while (in >> key) {
        if (key == "mode") { in >> val; meta.mode = ParseMode(val); }
        else if (key == "n_records") in >> meta.n_records;
    }
    return meta;
}

}  // namespace readmit
