// Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
//
// readmit.hpp: shared definitions for the encrypted 30-day readmission scorer.
//
// The application is four separate programs, one per role:
//
//   keygen   (hospital) makes all keys; the secret key stays put
//   encrypt  (hospital) clips inputs to the published box, packs, encrypts
//   server   (vendor)   computes the risk band without any key to read with
//   decrypt  (hospital) recovers the band
//
// The circuit itself lives in ONE function, run_circuit(), which every run mode
// calls. That is what stops the local, simulated and deployed runs from quietly
// computing different things.
#pragma once

#include "openfhe.h"

#include "ciphertext-ser.h"
#include "cryptocontext-ser.h"
#include "key/key-ser.h"
#include "scheme/ckksrns/ckksrns-ser.h"

#include <cmath>
#include <cstdint>
#include <filesystem>
#include <string>
#include <vector>

using namespace lbcrypto;

namespace readmit {

// Which of the two request shapes this run uses. Both evaluate the same model
// and the same band polynomial; they differ only in how patients are packed.
enum class Mode {
    Batch,      // column-major: one ciphertext per field, one slot per patient
    PerRecord,  // one patient's fields inside a single ciphertext
};

const char* ModeName(Mode m);
Mode ParseMode(const std::string& s);

// ── what the HOSPITAL is allowed to know ──────────────────────────────────
// The client must build a matching encryption context and pack its fields in
// the agreed order. None of that requires the vendor's weights, so the client
// programs read this and never the model.
struct PublicParams {
    int    n_features          = 0;
    int    feature_slot_stride = 0;
    usint  ring_dim            = 65536;
    usint  mult_depth          = 12;
    usint  scaling_mod_size    = 45;
    usint  first_mod_size      = 60;
    double noise_tolerance     = 0.0;
    // The range the band polynomial can legitimately produce. A decrypted value
    // outside it means the computation did not return intact. Values BETWEEN
    // whole numbers are normal: a patient near a band threshold decrypts to a
    // fraction by design, so "close to an integer" is NOT a health check.
    double band_value_min      = 0.0;
    double band_value_max      = 0.0;
    std::vector<std::string> feature_names;
};

// Reads model/circuit.txt. **Throws if the file contains any server-only field**
// (weights, bias, thresholds, ...), so handing a client the wrong file is a
// loud failure rather than a silent disclosure of the vendor's model.
PublicParams LoadPublicParams(const std::filesystem::path& file);

// ── the model, loaded from model.txt (server home only; it holds the weights)
struct Model {
    int    n_features          = 0;
    std::vector<double> weights;
    double bias                = 0.0;
    double threshold_moderate  = 0.0;
    double threshold_high      = 0.0;
    double steepness           = 0.0;
    uint32_t degree            = 0;
    double domain_lo           = 0.0;
    double domain_hi           = 0.0;

    usint  ring_dim            = 65536;
    usint  mult_depth          = 12;
    usint  scaling_mod_size    = 45;
    usint  first_mod_size      = 60;
    int    feature_slot_stride = 32;
};

Model LoadModel(const std::filesystem::path& file);

// The smooth two-step staircase the band polynomial approximates.
//
//   ~0 below the moderate threshold, ~1 between, ~2 above the high threshold.
//
// A sharp comparison is impossible under encryption (which can only add and
// multiply), so the steps are rendered as logistic curves and the whole
// staircase is fitted by a single polynomial. `steepness` sets how abruptly each
// step rises; it was chosen by sweeping against the plaintext reference.
inline double BandStaircase(double s, const Model& m) {
    return 1.0 / (1.0 + std::exp(-m.steepness * (s - m.threshold_moderate)))
         + 1.0 / (1.0 + std::exp(-m.steepness * (s - m.threshold_high)));
}

// ── context and key material ──────────────────────────────────────────────
// Ring dimension is set explicitly rather than inferred from the slot count: an
// under-set ring silently drops below the security floor and fails key
// generation after the build has already been paid for.
CryptoContext<DCRTPoly> BuildContext(usint ring_dim, usint mult_depth,
                                     usint scaling_mod_size, usint first_mod_size);
inline CryptoContext<DCRTPoly> BuildContext(const PublicParams& p) {
    return BuildContext(p.ring_dim, p.mult_depth, p.scaling_mod_size,
                        p.first_mod_size);
}

// Rotation amounts needed by PerRecord mode (powers of two below the stride).
// Batch mode needs none at all, which is why it generates no rotation keys,
// normally the dominant key cost.
std::vector<int32_t> RotationIndices(int feature_slot_stride);

void SaveContextAndKeys(const std::filesystem::path& home,
                        const CryptoContext<DCRTPoly>& cc,
                        const KeyPair<DCRTPoly>& kp);

// Loads the context plus evaluation keys. Never touches the secret key.
CryptoContext<DCRTPoly> LoadContextWithEvalKeys(const std::filesystem::path& home);

PublicKey<DCRTPoly>  LoadPublicKey(const std::filesystem::path& home,
                                   const CryptoContext<DCRTPoly>& cc);
PrivateKey<DCRTPoly> LoadSecretKey(const std::filesystem::path& home,
                                   const CryptoContext<DCRTPoly>& cc);

// ── the published input box (client side; contains ranges, never weights) ──
struct Bounds {
    std::vector<std::string> names;
    std::vector<double> lo, hi;
};
// Rejects a range with hi <= lo or a non-finite endpoint. Such a row makes
// ClipScale return inf/NaN, and CKKS encoding mixes every slot, so one NaN
// reaches every patient in the batch.
Bounds LoadBounds(const std::filesystem::path& csv);

// Clip a raw field value to its published range and map it to [0,1].
//
// Clipping admits every patient, so one extreme record cannot spoil a batch.
// It also bounds the score: with every field in [0,1] and the weights fixed,
// the score cannot leave [bias + sum(min(w,0)), bias + sum(max(w,0))], which is
// the interval the band polynomial was fitted to.
inline double ClipScale(double raw, double lo, double hi) {
    const double c = raw < lo ? lo : (raw > hi ? hi : raw);
    return (c - lo) / (hi - lo);
}

// ── plaintext operands ────────────────────────────────────────────────────
// Every plaintext the circuit multiplies by is built and tagged BEFORE recording
// starts. A plaintext constructed inside the recording bracket is read as
// uninitialised on replay, which shows up as a wrong answer rather than an error.
struct CircuitPlaintexts {
    std::vector<Plaintext> weight_cols;  // Batch: one per field, weight broadcast
    Plaintext weights_packed;            // PerRecord: weights across slots
    Plaintext bias_all;                  // both: the bias in every slot
};

CircuitPlaintexts MakePlaintexts(const CryptoContext<DCRTPoly>& cc,
                                 const Model& m, Mode mode, size_t slots);

// ── THE CIRCUIT ───────────────────────────────────────────────────────────
// One definition, called by every run mode (local CPU, simulator, deployed).
//
//   score = sum_j (weight_j x field_j) + bias        1 level
//   band  = P(score)                                 9 levels
//
// A note on why no slot masking is needed before the polynomial, which is the
// usual trap here. In PerRecord mode the rotate-and-sum leaves PARTIAL sums in
// the slots other than slot 0. Those are harmless: a partial sum ranges over a
// subset of the same weighted terms, so it is bounded by the full sum's range
// and therefore also lands inside the polynomial's fitted interval. In Batch
// mode the unused slots hold 0 + bias, likewise inside it. Every slot is in
// range, so no masking step and no extra multiplicative level are spent.
//
// `pt` is taken by non-const reference because OpenFHE's ciphertext x plaintext
// overloads bind a mutable Plaintext&.
Ciphertext<DCRTPoly> run_circuit(const CryptoContext<DCRTPoly>& cc,
                                 const Model& m, Mode mode,
                                 const std::vector<Ciphertext<DCRTPoly>>& in,
                                 CircuitPlaintexts& pt);

// ── file layout inside a home directory ───────────────────────────────────
namespace files {
inline constexpr const char* kContext   = "cc.bin";
inline constexpr const char* kPublicKey = "pk.bin";
inline constexpr const char* kSecretKey = "sk.bin";   // client home ONLY
inline constexpr const char* kMultKey   = "mk.bin";
inline constexpr const char* kRotKey    = "rk.bin";
inline constexpr const char* kModel     = "model.txt";    // server home ONLY
inline constexpr const char* kCircuit   = "circuit.txt";  // public, both homes
inline constexpr const char* kResult    = "ct_result.bin";
inline constexpr const char* kMeta      = "meta.txt";
}  // namespace files

// Input ciphertext filename: batch column j, or the single per-record input.
std::string InputFile(Mode mode, int j);

// Small metadata record travelling with a request: which shape, how many
// patients. Not secret; the vendor can see batch size anyway from slot counts.
struct Meta { Mode mode = Mode::Batch; int n_records = 1; };
void SaveMeta(const std::filesystem::path& home, const Meta& meta);
Meta LoadMeta(const std::filesystem::path& home);

}  // namespace readmit
