// Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
//
// server: runs on the VENDOR's machine, which the hospital does not trust.
//
// It holds the model and the evaluation keys. It does NOT hold the decryption
// key, so every value it touches, whether inputs, intermediates or the answer, is
// opaque to it. It cannot read a patient record even if it wants to.
//
// This program exits with status 2 if a secret key is present in its home
// directory when it starts.
//
// Four run modes over one circuit:
//   --cpu       plain local computation (the correctness gate)
//   --sim       record the computation, replay it through the local simulator
//   --sim-full  as --sim but with real maths recorded, adding a bit-level check
//   (no flag)   record and dispatch to the Niobium Fog
//
//   rescrubbed_server <home> [--cpu|--sim] [--hollow] [--no-ring-dim-check]

#include "rescrubbed.hpp"

#ifdef NIOBIUM_COMPILER
#include <niobium/compiler.h>
#else
#error "server.cpp must be built with -DNIOBIUM_COMPILER"
#endif

#include <chrono>
#include <cstdlib>
#include <iostream>

namespace fs = std::filesystem;

int main(int argc, char* argv[]) try {
    // init() consumes --hollow, --target and the optimisation level, and
    // compacts them out of argv.
    niobium::compiler().init(argc, argv);
    niobium::compiler().set_program_info(
        "rescrubbed_server", "1.0",
        "30-day hospital readmission risk banding on encrypted patient records");
    niobium::compiler().set_build_info(__FILE__, __LINE__, __TIMESTAMP__);

    std::string home_s;
    bool cpu_only = false, sim = false;
    for (int i = 1; i < argc; ++i) {
        std::string a = argv[i];
        if      (a == "--cpu") cpu_only = true;
        else if (a == "--sim") sim = true;
        else if (a == "--no-ring-dim-check") { /* forwarded to the recorder */ }
        else if (a == "--target" && i + 1 < argc) { ++i; }        // consumed by init()
        else if (a == "--opt-level" && i + 1 < argc) { ++i; }     // consumed by init()
        else if (a.size() == 3 && a.rfind("-O", 0) == 0) { }      // consumed by init()
        else if (a == "-h" || a == "--help") {
            std::cerr << "Usage: " << argv[0]
                      << " <home> [--cpu|--sim] [--hollow] [--no-ring-dim-check]\n";
            return 0;
        }
        else if (a.rfind("--", 0) == 0) { std::cerr << "Unknown arg: " << a << "\n"; return 1; }
        else if (home_s.empty()) home_s = a;
    }
    if (home_s.empty()) {
        std::cerr << "Usage: " << argv[0]
                  << " <home> [--cpu|--sim] [--hollow] [--no-ring-dim-check]\n";
        return 1;
    }
    const fs::path home = home_s;

    // ── the trust boundary, enforced ──────────────────────────────────────
    // A reviewer can test this: drop a secret key into the server home and
    // confirm the process aborts rather than starting.
    if (fs::exists(home / rescrubbed::files::kSecretKey)) {
        std::cerr << "[server] FATAL: a secret key is present in the server home ("
                  << (home / rescrubbed::files::kSecretKey).string() << ").\n"
                  << "[server] This process must never be able to decrypt. Refusing to start.\n";
        return 2;
    }

    const auto model = rescrubbed::LoadModel(home / rescrubbed::files::kModel);
    const auto meta  = rescrubbed::LoadMeta(home);

    auto cc = rescrubbed::LoadContextWithEvalKeys(home);
    const size_t slots = cc->GetEncodingParams()->GetBatchSize();

    // ── load the encrypted request ────────────────────────────────────────
    std::vector<Ciphertext<DCRTPoly>> in;
    const int n_ct = (meta.mode == rescrubbed::Mode::Batch) ? model.n_features : 1;
    size_t in_bytes = 0;
    for (int j = 0; j < n_ct; ++j) {
        const auto path = home / rescrubbed::InputFile(meta.mode, j);
        Ciphertext<DCRTPoly> ct;
        if (!Serial::DeserializeFromFile(path.string(), ct, SerType::BINARY))
            throw std::runtime_error("cannot load " + path.string());
        in_bytes += fs::file_size(path);
        in.push_back(std::move(ct));
    }
    std::cout << "[server] received " << in_bytes << " bytes of ciphertext ("
              << in_bytes / 1048576.0 << " MiB, " << n_ct << " ciphertext(s), mode="
              << rescrubbed::ModeName(meta.mode) << ", " << meta.n_records
              << " patient(s)), contents unreadable to this process\n";

    // Every plaintext operand the circuit multiplies by is built HERE, before
    // any recording starts. One built inside the recording bracket would be read
    // as uninitialised on replay.
    auto pt = rescrubbed::MakePlaintexts(cc, model, meta.mode, slots);

    Ciphertext<DCRTPoly> result;
    const auto t0 = std::chrono::steady_clock::now();

    if (cpu_only) {
        // Plain local computation, no recorder.
        result = rescrubbed::run_circuit(cc, model, meta.mode, in, pt);
    } else {
        // Recorded path: --sim replays locally, the default dispatches to the Fog.
        niobium::Compiler::CacheParameters cache = {
            {"workload", "rescrubbed"},
            {"mode", rescrubbed::ModeName(meta.mode)},
            {"degree", std::to_string(model.degree)},
            {"features", std::to_string(model.n_features)},
        };
        niobium::compiler().cache_parameters(cache);

        niobium::compiler().capture_crypto_context(cc);
        for (int j = 0; j < n_ct; ++j)
            niobium::compiler().tag_input("x" + std::to_string(j), in[j]);
        if (meta.mode == rescrubbed::Mode::Batch) {
            for (int j = 0; j < model.n_features; ++j)
                niobium::compiler().tag_input("w" + std::to_string(j), pt.weight_cols[size_t(j)]);
        } else {
            niobium::compiler().tag_input("w", pt.weights_packed);
        }
        niobium::compiler().tag_input("bias", pt.bias_all);
        niobium::compiler().tag_keys(cc);

        const bool hollow = niobium::compiler().is_hollow_mode();

        if (!niobium::compiler().is_cache_valid()) {
            niobium::compiler().enable_hollow_mode(hollow);
            niobium::compiler().start();
            result = rescrubbed::run_circuit(cc, model, meta.mode, in, pt);   // THE SHARED CIRCUIT
            niobium::compiler().probe("band", result);
            niobium::compiler().stop();
            niobium::compiler().enable_hollow_mode(false);
        }

        auto cpu_baseline = result;   // valid only on a real-maths record

        if (!niobium::compiler().replay()) {
            std::cerr << "[server] replay failed\n";
            return 1;
        }
        if (!niobium::compiler().result(cc, "band", result)) {
            std::cerr << "[server] result() failed\n";
            return 1;
        }

        // Free ring-level identity check, available only on a real-maths record
        // (under hollow the record pass produced no genuine ciphertext). A
        // mismatch here means the trace did not reproduce the computation, a
        // toolchain problem, not a design problem.
        //
        // Say so out loud when it does NOT run. It is the only thing --sim-full
        // adds over --sim, and on a cached trace there is no locally computed
        // baseline to compare against, so it would otherwise be skipped in
        // silence and read as having passed.
        if (!hollow && !cpu_baseline) {
            std::cout << "[server] ring-level identity check SKIPPED: the trace "
                         "was cached, so this run computed no local baseline. "
                         "Clear rescrubbed_server_workload_* to force it.\n";
        }
        if (!hollow && cpu_baseline) {
            const auto& a = result->GetElements();
            const auto& b = cpu_baseline->GetElements();
            bool identical = (a.size() == b.size());
            for (size_t i = 0; identical && i < a.size(); ++i) identical = (a[i] == b[i]);
            std::cout << "[server] ring-level identity vs local OpenFHE: "
                      << (identical ? "BIT-IDENTICAL" : "MISMATCH") << "\n";
            if (!identical) return 1;
        }
    }

    const double secs = std::chrono::duration<double>(
        std::chrono::steady_clock::now() - t0).count();

    // Drop the unused modulus towers before serialising. The circuit finishes
    // with spare levels it will never spend, and each one is a full polynomial
    // per ciphertext on the wire. The band is a small number read by rounding,
    // so one tower carries it with room to spare.
    //
    // COMPRESS_TOWERS exists to check that claim rather than assume it: the
    // harness sweeps it and confirms the decrypted bands are unchanged.
    unsigned towers = 1;
    if (const char* e = std::getenv("COMPRESS_TOWERS")) towers = unsigned(std::stoul(e));
    if (towers > 0) result = cc->Compress(result, towers);

    const auto out = home / rescrubbed::files::kResult;
    if (!Serial::SerializeToFile(out.string(), result, SerType::BINARY))
        throw std::runtime_error("failed to write " + out.string());
    const auto out_bytes = fs::file_size(out);

    std::cout << "[server] circuit complete in " << secs << "s (mode="
              << (cpu_only ? "cpu" : (sim ? "sim" : "fog")) << ")\n";
    std::cout << "[server] returned " << out_bytes << " bytes ("
              << out_bytes / 1048576.0 << " MiB), still encrypted. "
              << "this process never saw a score or a band\n";
    return 0;
} catch (const std::exception& e) {
    std::cerr << "[server] error: " << e.what() << "\n";
    return 1;
}
