# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Stage 3: build the plaintext REFERENCE model, the ground truth answer key.

This is the full-precision, unencrypted computation that every later version is
measured against. Nothing here is FHE-shaped: it uses a true sigmoid and exact
threshold comparisons.

Pipeline
--------
1.  Cohort selection (standard for this dataset, per Strack et al. 2014):
      - drop encounters ending in death or hospice transfer (the patient cannot
        be readmitted, so keeping them teaches the model the wrong lesson)
      - keep only each patient's FIRST encounter, so no patient appears in both
        the training and test splits
2.  Feature construction into a fixed, bounded [0,1] box (see FEATURES below).
    Every feature is clipped to a published clinical range and min-max mapped.
    The clipping bounds the score the encrypted stage evaluates.
3.  Grouped train/test split by patient.
4.  Fit L2-regularised logistic regression (scikit-learn, BSD-licensed; it also
    serves as the external oracle for the Stage 7 twin comparison).
5.  Fit a gradient-boosting model on the same features, NOT to deploy, but to
    measure the achievable ceiling on this feature set so the linear model's
    score can be read against something.
6.  Choose the two risk-band thresholds on the linear score.

Outputs
-------
    model/model.json          weights, bias, band thresholds, feature order
    data/feature_bounds.csv   the published input box (ranges only, NO weights)
    data/test_records.csv     held-out raw records for the encrypted pipeline
    data/test_features.npy    the same records as the [0,1] feature matrix
    data/test_labels.npy      true 30-day readmission outcomes
    reports/reference_metrics.json
"""

from __future__ import annotations

import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    average_precision_score,
    precision_recall_fscore_support,
    roc_auc_score,
)
from sklearn.model_selection import GroupShuffleSplit

warnings.filterwarnings("ignore")

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
MODEL = ROOT / "model"
REPORTS = ROOT / "reports"
for d in (DATA, MODEL, REPORTS):
    d.mkdir(exist_ok=True)

RANDOM_STATE = 20260811

# Discharge dispositions meaning the patient died or went to hospice. A patient
# who died cannot be readmitted; leaving these in makes "will not return" look
# predictable for the wrong reason.
DEAD_OR_HOSPICE = {11, 13, 14, 19, 20, 21}

# ICD-9 primary-diagnosis groupings, the conventional 9 buckets used in the
# published work on this dataset.
def diag_group(code) -> str:
    if pd.isna(code):
        return "other"
    s = str(code)
    if s.startswith("V") or s.startswith("E"):
        return "other"
    try:
        v = float(s)
    except ValueError:
        return "other"
    if 390 <= v <= 459 or int(v) == 785:
        return "circulatory"
    if 460 <= v <= 519 or int(v) == 786:
        return "respiratory"
    if 520 <= v <= 579 or int(v) == 787:
        return "digestive"
    if int(v) == 250:
        return "diabetes"
    if 800 <= v <= 999:
        return "injury"
    if 710 <= v <= 739:
        return "musculoskeletal"
    if 580 <= v <= 629 or int(v) == 788:
        return "genitourinary"
    if 140 <= v <= 239:
        return "neoplasm"
    return "other"


AGE_MID = {
    "[0-10)": 5, "[10-20)": 15, "[20-30)": 25, "[30-40)": 35, "[40-50)": 45,
    "[50-60)": 55, "[60-70)": 65, "[70-80)": 75, "[80-90)": 85, "[90-100)": 95,
}

# (name, lo, hi): the published input box. Every feature is clipped here and
# mapped to [0,1]. Continuous bounds are set at a high percentile so the clip
# saturates genuine outliers rather than reshaping the bulk of the distribution.
FEATURES: list[tuple[str, float, float]] = [
    ("time_in_hospital",       1,  14),
    ("num_lab_procedures",     0, 100),
    ("num_procedures",         0,   6),
    ("num_medications",        0,  40),
    ("number_outpatient",      0,   5),
    ("number_emergency",       0,   3),
    ("number_inpatient",       0,   5),
    ("number_diagnoses",       1,   9),
    ("age_years",              5,  95),
    ("gender_female",          0,   1),
    ("adm_emergency",          0,   1),
    ("adm_urgent",             0,   1),
    ("src_emergency_room",     0,   1),
    ("not_discharged_home",    0,   1),
    ("a1c_high",               0,   1),
    ("a1c_normal",             0,   1),
    ("glucose_abnormal",       0,   1),
    ("med_change",             0,   1),
    ("on_diabetes_meds",       0,   1),
    ("on_insulin",             0,   1),
    ("diag_circulatory",       0,   1),
    ("diag_respiratory",       0,   1),
    ("diag_digestive",         0,   1),
    ("diag_diabetes",          0,   1),
    ("diag_injury",            0,   1),
    ("diag_musculoskeletal",   0,   1),
    ("diag_genitourinary",     0,   1),
    ("diag_neoplasm",          0,   1),
]
FEATURE_NAMES = [f[0] for f in FEATURES]
LO = np.array([f[1] for f in FEATURES], dtype=np.float64)
HI = np.array([f[2] for f in FEATURES], dtype=np.float64)


def build_raw_frame(df: pd.DataFrame) -> pd.DataFrame:
    """Derive the raw (pre-clip, pre-scale) feature columns from the encounter."""
    out = pd.DataFrame(index=df.index)
    out["time_in_hospital"] = df["time_in_hospital"]
    out["num_lab_procedures"] = df["num_lab_procedures"]
    out["num_procedures"] = df["num_procedures"]
    out["num_medications"] = df["num_medications"]
    out["number_outpatient"] = df["number_outpatient"]
    out["number_emergency"] = df["number_emergency"]
    out["number_inpatient"] = df["number_inpatient"]
    out["number_diagnoses"] = df["number_diagnoses"]
    out["age_years"] = df["age"].map(AGE_MID).fillna(65)

    out["gender_female"] = (df["gender"] == "Female").astype(int)
    out["adm_emergency"] = (df["admission_type_id"] == 1).astype(int)
    out["adm_urgent"] = (df["admission_type_id"] == 2).astype(int)
    out["src_emergency_room"] = (df["admission_source_id"] == 7).astype(int)
    out["not_discharged_home"] = (~df["discharge_disposition_id"].isin([1])).astype(int)

    a1c = df["A1Cresult"].fillna("None")
    out["a1c_high"] = a1c.isin([">7", ">8"]).astype(int)
    out["a1c_normal"] = (a1c == "Norm").astype(int)
    glu = df["max_glu_serum"].fillna("None")
    out["glucose_abnormal"] = glu.isin([">200", ">300"]).astype(int)

    out["med_change"] = (df["change"] == "Ch").astype(int)
    out["on_diabetes_meds"] = (df["diabetesMed"] == "Yes").astype(int)
    out["on_insulin"] = (~df["insulin"].fillna("No").isin(["No"])).astype(int)

    grp = df["diag_1"].map(diag_group)
    for g in ["circulatory", "respiratory", "digestive", "diabetes", "injury",
              "musculoskeletal", "genitourinary", "neoplasm"]:
        out[f"diag_{g}"] = (grp == g).astype(int)

    return out[FEATURE_NAMES]


def scale_box(raw: np.ndarray) -> np.ndarray:
    """Clip to the published box and min-max map to [0,1].

    Clipping (winsorising) rather than rejecting is deliberate: every record is
    admitted, so a batched encrypted run can never be spoiled by one extreme
    patient, and the reject rate is zero by construction. Saturating an extreme
    value at the bound still means 'extreme', which is exactly what these
    continuous clinical counts encode.
    """
    return (np.clip(raw, LO, HI) - LO) / (HI - LO)


def main() -> None:
    print("Loading encounters...", flush=True)
    df = pd.read_csv(DATA / "raw_encounters.csv", low_memory=False)
    n0 = len(df)

    df = df[~df["discharge_disposition_id"].isin(DEAD_OR_HOSPICE)]
    n1 = len(df)
    df = df.sort_values("encounter_id").drop_duplicates("patient_nbr", keep="first")
    n2 = len(df)
    print(f"  {n0:,} encounters")
    print(f"  {n1:,} after dropping death/hospice discharges  (-{n0-n1:,})")
    print(f"  {n2:,} after keeping first encounter per patient (-{n1-n2:,})")

    y = (df["readmitted"] == "<30").astype(int).to_numpy()
    raw = build_raw_frame(df)
    groups = df["patient_nbr"].to_numpy()
    print(f"  base rate (readmitted <30d): {y.mean():.4f}  ({y.sum():,} positives)")

    X = scale_box(raw.to_numpy(dtype=np.float64))

    # --- degeneracy check: fail loudly on a rank-deficient design matrix -----
    Xd = np.column_stack([X, np.ones(len(X))])
    rank = np.linalg.matrix_rank(Xd)
    cond = np.linalg.cond(Xd)
    print(f"\n  design matrix rank {rank}/{Xd.shape[1]}, condition number {cond:.1f}")
    assert rank == Xd.shape[1], (
        f"Rank-deficient feature matrix ({rank} < {Xd.shape[1]}): some feature is an "
        "exact linear combination of the others and buys ciphertext ops for nothing."
    )

    # --- split by patient ---------------------------------------------------
    gss = GroupShuffleSplit(n_splits=1, test_size=0.25, random_state=RANDOM_STATE)
    tr, te = next(gss.split(X, y, groups=groups))
    Xtr, Xte, ytr, yte = X[tr], X[te], y[tr], y[te]
    print(f"  train {len(tr):,}   test {len(te):,}"
          f"   (test base rate {yte.mean():.4f})")

    # --- the reference model ------------------------------------------------
    print("\nFitting reference model (L2 logistic regression)...", flush=True)
    clf = LogisticRegression(C=1.0, max_iter=5000, solver="lbfgs")
    clf.fit(Xtr, ytr)
    w = clf.coef_[0].astype(np.float64)
    b = float(clf.intercept_[0])

    score_te = Xte @ w + b
    auc = roc_auc_score(yte, score_te)
    ap = average_precision_score(yte, score_te)

    # --- achievable ceiling on this feature set -----------------------------
    print("Fitting ceiling comparator (gradient boosting, not deployed)...", flush=True)
    gb = HistGradientBoostingClassifier(
        max_iter=300, learning_rate=0.06, max_leaf_nodes=31,
        l2_regularization=1.0, random_state=RANDOM_STATE,
    )
    gb.fit(Xtr, ytr)
    gb_auc = roc_auc_score(yte, gb.predict_proba(Xte)[:, 1])

    # --- risk bands ---------------------------------------------------------
    # Bands are set on the TRAINING score distribution so the test evaluation
    # stays honest. High = top 15% of risk (the group a transitional-care
    # programme could realistically absorb); moderate = next 25%.
    score_tr = Xtr @ w + b
    t_hi = float(np.quantile(score_tr, 0.85))
    t_mod = float(np.quantile(score_tr, 0.60))

    band_te = (score_te > t_mod).astype(int) + (score_te > t_hi).astype(int)
    high = band_te == 2
    prec, rec, f1, _ = precision_recall_fscore_support(
        yte, high.astype(int), average="binary", zero_division=0
    )

    print("\n" + "=" * 66)
    print("REFERENCE MODEL: quality against ground truth (held-out patients)")
    print("=" * 66)
    print(f"  AUC (ranking quality)            {auc:.4f}")
    print(f"     published logistic regression  ~0.642   [Liu et al., JMAI]")
    print(f"     published XGBoost (best)       ~0.667   [MDPI Healthcare 2026]")
    print(f"     gradient boosting, our features {gb_auc:.4f}   <- achievable ceiling")
    print(f"     random guessing                 0.5000")
    print(f"  Average precision                {ap:.4f}   (base rate {yte.mean():.4f})")
    print(f"\n  Risk bands (thresholds on the score, from the training split):")
    print(f"     moderate  score > {t_mod:+.4f}")
    print(f"     high      score > {t_hi:+.4f}")
    for lvl, name in enumerate(["low", "moderate", "high"]):
        m = band_te == lvl
        print(f"     {name:9s} {m.sum():6,d} patients ({m.mean():5.1%})"
              f"   readmission rate {yte[m].mean():.1%}")
    print(f"\n  High-risk flag as a detector of 30-day readmission:")
    print(f"     precision {prec:.4f}   recall {rec:.4f}   F1 {f1:.4f}")
    print(f"     lift over base rate: {yte[high].mean()/yte.mean():.2f}x")
    print("=" * 66)

    # --- persist ------------------------------------------------------------
    (MODEL / "model.json").write_text(json.dumps({
        "description": "L2 logistic regression, 30-day readmission risk. "
                       "Weights act on features already clipped to the published "
                       "box and min-max mapped to [0,1].",
        "feature_names": FEATURE_NAMES,
        "weights": w.tolist(),
        "bias": b,
        "threshold_moderate": t_mod,
        "threshold_high": t_hi,
        "score_min_provable": float(b + np.minimum(w, 0).sum()),
        "score_max_provable": float(b + np.maximum(w, 0).sum()),
    }, indent=2))

    pd.DataFrame({"feature": FEATURE_NAMES, "lo": LO, "hi": HI}).to_csv(
        DATA / "feature_bounds.csv", index=False)

    raw.iloc[te].assign(readmitted_30d=yte).to_csv(DATA / "test_records.csv", index=False)
    np.save(DATA / "test_features.npy", Xte)
    np.save(DATA / "test_labels.npy", yte)

    (REPORTS / "reference_metrics.json").write_text(json.dumps({
        "n_encounters_raw": int(n0),
        "n_after_cohort": int(n2),
        "n_train": int(len(tr)), "n_test": int(len(te)),
        "base_rate_test": float(yte.mean()),
        "auc": float(auc),
        "auc_gradient_boosting_ceiling": float(gb_auc),
        "auc_published_logreg": 0.642,
        "auc_published_xgboost_best": 0.667,
        "average_precision": float(ap),
        "threshold_moderate": t_mod, "threshold_high": t_hi,
        "high_band_precision": float(prec),
        "high_band_recall": float(rec),
        "high_band_f1": float(f1),
        "band_fractions": {
            n: float((band_te == i).mean()) for i, n in
            enumerate(["low", "moderate", "high"])
        },
        "band_readmission_rates": {
            n: float(yte[band_te == i].mean()) for i, n in
            enumerate(["low", "moderate", "high"])
        },
    }, indent=2))

    print(f"\nWrote model/model.json, data/feature_bounds.csv, "
          f"data/test_records.csv ({len(te):,} rows), reports/reference_metrics.json")

    # --- provable operand bound (Stage 6 input) -----------------------------
    lo_s = b + np.minimum(w, 0).sum()
    hi_s = b + np.maximum(w, 0).sum()
    print(f"\nProvable score range over the whole input box: "
          f"[{lo_s:.4f}, {hi_s:.4f}]")
    print(f"Observed score range on the test set:            "
          f"[{score_te.min():.4f}, {score_te.max():.4f}]")


if __name__ == "__main__":
    main()
