# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Head-to-head: our model vs the LACE index, on the SAME cohort.

Published c-statistics for LACE (0.68) and HOSPITAL (0.71) come from different
populations with different outcome definitions, so quoting them beside our 0.635
would be misleading. The only fair comparison is to compute LACE on our exact
held-out patients and score both against the same labels.

LACE (van Walraven et al., CMAJ 2010) sums four components:
  L  length of stay        1d=1, 2d=2, 3d=3, 4-6d=4, 7-13d=5, >=14d=7
  A  acute/emergency admission                                        3
  C  Charlson comorbidity index   0=0, 1=1, 2=2, 3=3, >=4=5
  E  emergency visits in the prior 6 months  0..3 = 0..3, >=4=4

Two documented approximations, both of which handicap LACE slightly:
  * Charlson is derived from only three diagnosis codes (all this dataset
    records), so comorbidity is under-counted relative to a full problem list.
  * The dataset's emergency-visit count covers the prior YEAR, not six months,
    so this component is if anything over-counted.

HOSPITAL is not computed: it requires haemoglobin and sodium at discharge, which
this dataset does not contain. Stated rather than approximated away.
"""

from __future__ import annotations

import sys
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

warnings.filterwarnings("ignore")
sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_reference import (  # noqa: E402
    FEATURE_NAMES, RANDOM_STATE, build_raw_frame, cohort, scale_box,
)
from twin import load_model  # noqa: E402
from sklearn.model_selection import GroupShuffleSplit  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent


def icd9(code) -> float | None:
    if pd.isna(code):
        return None
    s = str(code).strip()
    if s.startswith(("V", "E")):
        return None
    try:
        return float(s)
    except ValueError:
        return None


# Deyo/Quan ICD-9 groupings for the Charlson index: (lo, hi, weight).
CHARLSON = [
    (410, 410.99, 1), (412, 412.99, 1),                       # myocardial infarction
    (428, 428.99, 1), (398.91, 398.91, 1),                    # heart failure
    (440, 441.99, 1), (443.9, 443.9, 1), (447.1, 447.1, 1),   # peripheral vascular
    (430, 438.99, 1),                                         # cerebrovascular
    (290, 290.99, 1), (294.1, 294.1, 1), (331.2, 331.2, 1),   # dementia
    (490, 505.99, 1), (506.4, 506.4, 1),                      # chronic pulmonary
    (710.0, 710.1, 1), (714.0, 714.2, 1), (725, 725.99, 1),   # rheumatic
    (531, 534.99, 1),                                         # peptic ulcer
    (571.2, 571.2, 1), (571.4, 571.6, 1),                     # mild liver disease
    (250.0, 250.39, 1), (250.8, 250.99, 1),                   # diabetes, uncomplicated
    (250.4, 250.79, 2),                                       # diabetes, end-organ damage
    (342, 344.69, 2),                                         # hemiplegia
    (582, 583.99, 2), (585, 586.99, 2), (588, 588.99, 2),     # renal disease
    (140, 172.99, 2), (174, 195.99, 2), (200, 208.99, 2),     # malignancy
    (456.0, 456.2, 3), (572.2, 572.8, 3),                     # severe liver disease
    (196, 199.99, 6),                                         # metastatic solid tumour
    (42, 44.99, 6),                                           # HIV/AIDS
]


def charlson_row(codes) -> int:
    """Highest-weight match per condition group, summed. Diabetes counted once."""
    hits: dict[int, int] = {}
    for c in codes:
        v = icd9(c)
        if v is None:
            continue
        for gi, (lo, hi, w) in enumerate(CHARLSON):
            if lo <= v <= hi:
                hits[gi] = max(hits.get(gi, 0), w)
    # Collapse the two diabetes tiers to the more severe one only.
    dm_simple = [i for i, (lo, hi, _) in enumerate(CHARLSON)
                 if lo in (250.0, 250.8)]
    dm_compl = [i for i, (lo, hi, _) in enumerate(CHARLSON) if lo == 250.4]
    if any(i in hits for i in dm_compl):
        for i in dm_simple:
            hits.pop(i, None)
    return sum(hits.values())


def lace_points(los: int, emergency: bool, charlson: int, ed_visits: int) -> int:
    if   los <= 3:  L = los
    elif los <= 6:  L = 4
    elif los <= 13: L = 5
    else:           L = 7
    A = 3 if emergency else 0
    C = min(charlson, 3) if charlson < 4 else 5
    E = min(ed_visits, 4)
    return L + A + C + E


def main() -> None:
    df = pd.read_csv(ROOT / "data" / "raw_encounters.csv", low_memory=False)
    df = cohort(df)

    y_all = (df["readmitted"] == "<30").astype(int).to_numpy()
    X_all = scale_box(build_raw_frame(df).to_numpy(dtype=np.float64))
    groups = df["patient_nbr"].to_numpy()

    # The identical split used to train and evaluate our model.
    gss = GroupShuffleSplit(n_splits=1, test_size=0.25, random_state=RANDOM_STATE)
    _, te = next(gss.split(X_all, y_all, groups=groups))

    sub = df.iloc[te]
    y = y_all[te]

    ch = np.array([charlson_row((r.diag_1, r.diag_2, r.diag_3))
                   for r in sub.itertuples()])
    lace = np.array([
        lace_points(int(r.time_in_hospital),
                    r.admission_type_id in (1, 2),      # emergency or urgent
                    int(c),
                    int(r.number_emergency))
        for r, c in zip(sub.itertuples(), ch)
    ])

    model = load_model()
    ours = X_all[te] @ np.asarray(model["weights"]) + model["bias"]

    auc_lace = roc_auc_score(y, lace)
    auc_ours = roc_auc_score(y, ours)

    print("=" * 74)
    print(" HEAD TO HEAD on the SAME 17,498 held-out patients")
    print("=" * 74)
    print(f"  base rate (readmitted within 30 days): {y.mean():.4f}\n")
    print(f"  {'model':<34} {'AUC':>7}   {'published elsewhere':>20}")
    print(f"  {'-'*34} {'-'*7}   {'-'*20}")
    print(f"  {'LACE index (computed here)':<34} {auc_lace:>7.4f}   "
          f"{'0.68 (other cohorts)':>20}")
    print(f"  {'our model (deployed encrypted)':<34} {auc_ours:>7.4f}   "
          f"{'0.642 logreg / 0.667 best':>20}")
    print(f"  {'random guessing':<34} {0.5:>7.4f}")
    print()

    # LACE's own high-risk convention is a score above 9.
    hi = lace >= 10
    print(f"  LACE high-risk (score >= 10): {hi.sum():,} patients ({hi.mean():.1%}), "
          f"{y[hi].mean():.1%} readmitted  ({y[hi].mean()/y.mean():.2f}x base rate)")
    ours_hi = ours > model["threshold_high"]
    print(f"  our high band:                {ours_hi.sum():,} patients "
          f"({ours_hi.mean():.1%}), {y[ours_hi].mean():.1%} readmitted  "
          f"({y[ours_hi].mean()/y.mean():.2f}x base rate)")
    print()
    print(f"  LACE score range observed: {lace.min()}-{lace.max()} "
          f"(median {int(np.median(lace))}); Charlson median {int(np.median(ch))}")
    print("=" * 74)
    print("  Caveats: Charlson derived from 3 diagnosis codes (all this dataset")
    print("  records), so comorbidity is under-counted; the emergency-visit count")
    print("  covers a year rather than six months. HOSPITAL is not computable here")
    print("  at all. It needs haemoglobin and sodium at discharge.")
    print("=" * 74)


if __name__ == "__main__":
    main()
