# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Report an encrypted run: clinical quality first, then fidelity, then cost.

Clinical quality leads. The encrypted-vs-twin comparison can confirm that
encryption preserved the quality the design already had; it cannot create any.
The deployment profile comes last.

Exit status is the pass/fail of the encryption-fidelity check.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import precision_recall_fscore_support, roc_auc_score

sys.path.insert(0, str(Path(__file__).resolve().parent))
from twin import Twin, TwinConfig, load_model, reference_band  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
BAND_NAME = ["low", "moderate", "high"]


def load_box() -> tuple[list[str], np.ndarray, np.ndarray]:
    """Read the SAME published input box the encrypted client enforces.

    The CSV is the artifact the design emits and the client reads. Comparing
    against build_reference's hardcoded constants instead would report band
    differences produced by this script rather than by encryption.
    """
    rows = list(csv.DictReader(
        (ROOT / "data" / "feature_bounds.csv").read_text().splitlines()))
    return ([r["feature"] for r in rows],
            np.array([float(r["lo"]) for r in rows]),
            np.array([float(r["hi"]) for r in rows]))


def human(n: int) -> str:
    return f"{n/1048576:.1f} MiB" if n >= 1048576 else f"{n/1024:.1f} KiB"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--decrypted", required=True)
    ap.add_argument("--mode", required=True)
    ap.add_argument("--run-mode", required=True)
    ap.add_argument("--offset", type=int, default=0)
    ap.add_argument("--n", type=int, required=True)
    for k in ("keygen", "encrypt", "server", "decrypt"):
        ap.add_argument(f"--t-{k}", type=float, default=0.0)
    ap.add_argument("--bytes-in", type=int, default=0)
    ap.add_argument("--bytes-out", type=int, default=0)
    ap.add_argument("--bytes-keys", type=int, default=0)
    ap.add_argument("--peak-rss", default="n/a")
    a = ap.parse_args()

    cp = json.loads((ROOT / "model" / "circuit_params.json").read_text())
    model = load_model()

    # The same patients the encrypted run scored, clipped and scaled with the
    # same published box the client enforced.
    names, lo, hi = load_box()
    if names != cp["feature_names"]:
        print("[FAIL] data/feature_bounds.csv is not in the circuit's field order")
        return 1
    recs = pd.read_csv(ROOT / "data" / "test_records.csv")
    sl = recs.iloc[a.offset:a.offset + a.n]
    raw = sl[names].to_numpy(dtype=np.float64)
    X = (np.clip(raw, lo, hi) - lo) / (hi - lo)
    y = sl["readmitted_30d"].to_numpy()

    tw = Twin(model, TwinConfig(cp["steepness"], cp["degree"],
                                cp["scaling_mod_size"], cp["multiplicative_depth"]))
    twin_val = tw.band_value(X)
    twin_band = tw.band(X)
    ref = reference_band(X, model)

    dec = pd.read_csv(a.decrypted)
    fhe_val = dec["value"].to_numpy()
    fhe_band = dec["band"].to_numpy()
    n = len(fhe_band)
    if n != len(twin_band):
        print(f"[FAIL] decrypted {n} results, expected {len(twin_band)}")
        return 1

    twin_val, twin_band, ref, y, X = twin_val[:n], twin_band[:n], ref[:n], y[:n], X[:n]

    # ── (a) what the system is for ────────────────────────────────────────
    print()
    print("=" * 78)
    print(" WHAT THE ENCRYPTED SERVICE PREDICTED")
    print("=" * 78)

    if a.mode == "per_record":
        print(f"  One patient scored at discharge (test-set row {a.offset}).")
        print(f"    risk band returned : {BAND_NAME[int(fhe_band[0])]}")
        print(f"    actually readmitted within 30 days: "
              f"{'yes' if y[0] else 'no'}   (the ground-truth label)")
        print(f"\n  Population figures for this model, computed in the clear over")
        print(f"  the labelled test set, are in reports/results.md.")
    else:
        print(f"  {n:,} patients scored in a single encrypted request.\n")
        print(f"    {'band':<10} {'patients':>9} {'share':>8} "
              f"{'actually readmitted':>21}")
        for lvl in (0, 1, 2):
            m = fhe_band == lvl
            if not m.any():
                continue
            print(f"    {BAND_NAME[lvl]:<10} {m.sum():>9,} {m.mean():>7.1%} "
                  f"{y[m].mean():>20.1%}")
        print(f"    {'all':<10} {n:>9,} {1.0:>7.1%} {y.mean():>20.1%}")

        high = fhe_band == 2
        if high.any():
            p, r, f1, _ = precision_recall_fscore_support(
                y, high.astype(int), average="binary", zero_division=0)
            print(f"\n  Using the high band as a flag for 'likely to come back':")
            print(f"    of those flagged, {p:.1%} did return       (precision)")
            print(f"    of those who returned, {r:.1%} were flagged (recall)")
            print(f"    that is {y[high].mean()/y.mean():.2f}x the background rate "
                  f"of {y.mean():.1%}")

    # ── (b) did encryption change the answers? ────────────────────────────
    print()
    print("=" * 78)
    print(" DID ENCRYPTION CHANGE ANY ANSWER?")
    print("=" * 78)

    err = np.abs(fhe_val - twin_val)
    flips = int((fhe_band != twin_band).sum())
    tol = cp["noise_tolerance"]
    fid_ok = (flips == 0) and (err.max() < tol)

    print(f"  Compared against the faithful twin, a plaintext model of this exact")
    print(f"  computation, so any difference here is encryption noise alone.")
    print(f"    patients whose band changed : {flips} of {n:,}")
    print(f"    largest numeric difference  : {err.max():.3e}"
          f"   (budget {tol:.0e})")
    print(f"    typical difference          : {err.mean():.3e}")
    print(f"    verdict: {'PASS' if fid_ok else 'FAIL'}")

    ref_flips = int((fhe_band != ref).sum())
    print(f"\n  And against the original unencrypted model, end to end:")
    print(f"    patients banded differently : {ref_flips} of {n:,} "
          f"({(1-ref_flips/n)*100:.4f}% identical)")
    if ref_flips:
        idx = np.where(fhe_band != ref)[0]
        d = np.abs((X[idx] @ np.asarray(model["weights"]) + model["bias"])
                   - np.where(ref[idx] >= 2, model["threshold_high"],
                              model["threshold_moderate"]))
        print(f"    those patients sit within {d.max():.5f} of a band boundary "
              f"(score range spans {cp['domain_hi']-cp['domain_lo']:.2f})")

    # ── (c) deployment profile ────────────────────────────────────────────
    print()
    print("=" * 78)
    print(" WHAT IT COST")
    print("=" * 78)
    total = a.t_keygen + a.t_encrypt + a.t_server + a.t_decrypt
    print(f"  run mode: {a.run_mode}    request shape: {a.mode}")
    print(f"    key generation (one-off)   {a.t_keygen:8.2f} s")
    print(f"    encrypt   (hospital)       {a.t_encrypt:8.2f} s")
    print(f"    compute   (vendor)         {a.t_server:8.2f} s")
    print(f"    decrypt   (hospital)       {a.t_decrypt:8.2f} s")
    print(f"    {'total':<26} {total:8.2f} s"
          + (f"   ({a.t_server/n*1000:.2f} ms of compute per patient)"
             if n > 1 else ""))
    print(f"\n    uploaded  {human(a.bytes_in):>10}"
          + (f"   ({a.bytes_in/n/1024:.1f} KiB per patient)" if n > 1 else ""))
    print(f"    returned  {human(a.bytes_out):>10}")
    print(f"    keys sent once, at setup   {human(a.bytes_keys)}")
    print(f"    peak server memory         {a.peak_rss}")

    print()
    print("=" * 78)
    print(f" {'PASS' if fid_ok else 'FAIL'}: encryption "
          f"{'preserved every band' if fid_ok else 'changed results beyond tolerance'}")
    print("=" * 78)

    # Machine-readable, written beside the run's other artifacts under
    # run_<mode>/ rather than into reports/. A run is a build artifact: it must
    # leave the working tree clean. The authored documents (reports/results.md,
    # the README) are what carry these numbers forward.
    (Path(a.decrypted).resolve().parent / "summary.json").write_text(json.dumps({
        "run_mode": a.run_mode, "request_shape": a.mode, "n_patients": int(n),
        "band_flips_vs_twin": flips, "max_error_vs_twin": float(err.max()),
        "mean_error_vs_twin": float(err.mean()), "noise_tolerance": tol,
        "band_flips_vs_reference": ref_flips,
        "seconds": {"keygen": a.t_keygen, "encrypt": a.t_encrypt,
                    "server": a.t_server, "decrypt": a.t_decrypt},
        "bytes": {"input": a.bytes_in, "output": a.bytes_out, "keys": a.bytes_keys},
        "peak_server_rss": a.peak_rss,
        "pass": bool(fid_ok),
    }, indent=2))
    return 0 if fid_ok else 1


if __name__ == "__main__":
    sys.exit(main())
