# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Export the frozen design into the two files the encrypted programs read.

The hospital needs to build a matching encryption context and pack its fields
in the right order. None of that requires the weights, so the design emits two
files:

    model/circuit.txt   PUBLIC. Context parameters and the feature order.
                        Ships to both parties. Contains no weights.
    model/model.txt     SERVER ONLY. Everything, including the weights.

A client program handed a file containing weights raises an error naming the
offending field and stops.

Both are deployed data, not compiled-in constants, so the model can be updated
without rebuilding, and the twin and the C++ share one source of truth
(model/circuit_params.json, written by scripts/gate.py).
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
p = json.loads((ROOT / "model" / "circuit_params.json").read_text())
names = p["feature_names"]

# ── public: everything the hospital legitimately needs ──────────────────────
circuit = [
    "# Public circuit parameters for the 30-day readmission scorer.",
    "# Generated by scripts/export_model.py. Safe to ship to any client:",
    "# it contains NO model weights.",
    f"n_features {p['n_features']}",
    f"feature_slot_stride {p['feature_slot_stride']}",
    f"ring_dim {p['ring_dim']}",
    f"mult_depth {p['multiplicative_depth']}",
    f"scaling_mod_size {p['scaling_mod_size']}",
    f"first_mod_size {p['first_mod_size']}",
    f"noise_tolerance {p['noise_tolerance']!r}",
    # The range the band polynomial can legitimately produce. The client rejects
    # anything outside it, so a run that came back broken is reported rather than
    # rounded into a clinically actionable band. Values BETWEEN whole numbers are
    # normal here: a patient near a threshold decrypts to a fraction by design.
    f"band_value_min {p['band_value_min']!r}",
    f"band_value_max {p['band_value_max']!r}",
    # Pins the field order the client must pack in. Without it a reordered
    # bounds file would pair each field with the wrong weight, silently.
    "feature_names " + " ".join(names),
]
circuit_path = ROOT / "model" / "circuit.txt"
circuit_path.write_text("\n".join(circuit) + "\n")

# ── server only: the model itself ───────────────────────────────────────────
model = [
    "# 30-day readmission risk model + circuit parameters.",
    "# Generated by scripts/export_model.py from model/circuit_params.json.",
    "# CONTAINS MODEL WEIGHTS: this file belongs in the SERVER home only.",
    f"n_features {p['n_features']}",
    f"feature_slot_stride {p['feature_slot_stride']}",
    f"ring_dim {p['ring_dim']}",
    f"mult_depth {p['multiplicative_depth']}",
    f"scaling_mod_size {p['scaling_mod_size']}",
    f"first_mod_size {p['first_mod_size']}",
    f"noise_tolerance {p['noise_tolerance']!r}",
    f"bias {p['bias']!r}",
    f"threshold_moderate {p['threshold_moderate']!r}",
    f"threshold_high {p['threshold_high']!r}",
    f"steepness {p['steepness']!r}",
    f"degree {p['degree']}",
    f"domain_lo {p['domain_lo']!r}",
    f"domain_hi {p['domain_hi']!r}",
    "weights " + " ".join(repr(w) for w in p["weights"]),
]
model_path = ROOT / "model" / "model.txt"
model_path.write_text("\n".join(model) + "\n")

# ── consistency: the client's two artifacts must agree on the field order ───
bounds = list(csv.DictReader(
    (ROOT / "data" / "feature_bounds.csv").read_text().splitlines()))
assert [b["feature"] for b in bounds] == names, (
    "data/feature_bounds.csv is not in the model's feature order; the client "
    "would clip each field against the wrong range."
)
for b in bounds:
    assert float(b["hi"]) > float(b["lo"]), f"degenerate bound for {b['feature']}"

# Check for an actual `weights`/`bias`/threshold KEY, not the word appearing in a
# comment. Mirrors the guard the C++ client-side loader applies at runtime.
_secret_keys = {"weights", "bias", "threshold_moderate", "threshold_high",
                "steepness", "degree", "domain_lo", "domain_hi"}
for _line in circuit_path.read_text().splitlines():
    if _line.startswith("#") or not _line.strip():
        continue
    assert _line.split()[0] not in _secret_keys, (
        f"public circuit file leaked a server-only field: {_line.split()[0]}")

print(f"Wrote {circuit_path.relative_to(ROOT)}  "
      f"(public: {p['n_features']} features, no weights)")
print(f"Wrote {model_path.relative_to(ROOT)}  "
      f"(server only: weights, degree {p['degree']}, depth "
      f"{p['multiplicative_depth']})")
print(f"Verified data/feature_bounds.csv matches the field order and has no "
      f"degenerate ranges.")
