# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Download the UCI 'Diabetes 130-US Hospitals for Years 1999-2008' dataset.

Source: https://archive.ics.uci.edu/dataset/296/diabetes+130+us+hospitals+for+years+1999+2008
101,766 de-identified inpatient encounters from 130 US hospitals. The label used
here is the dataset's `readmitted` column, collapsed to a binary 30-day outcome.

Writes data/raw_encounters.csv and data/dataset_metadata.txt.
"""

import os
import ssl
import sys
from pathlib import Path

import certifi

# macOS python builds often ship no CA bundle; point urllib at certifi's.
os.environ.setdefault("SSL_CERT_FILE", certifi.where())
ssl._create_default_https_context = lambda *a, **k: ssl.create_default_context(
    cafile=certifi.where()
)

from ucimlrepo import fetch_ucirepo  # noqa: E402

OUT = Path(__file__).resolve().parent.parent / "data"
OUT.mkdir(exist_ok=True)


def main() -> int:
    print("Fetching UCI dataset 296 (Diabetes 130-US Hospitals)...", flush=True)
    repo = fetch_ucirepo(id=296)

    X = repo.data.features
    y = repo.data.targets
    ids = repo.data.ids

    # patient_nbr is needed to keep repeat visits by the same patient out of both
    # the training and the test split. Without it the model can memorise a
    # patient rather than learn a pattern, and the reported quality is inflated.
    df = ids.copy()
    for col in X.columns:
        df[col] = X[col]
    for col in y.columns:
        df[col] = y[col]

    path = OUT / "raw_encounters.csv"
    df.to_csv(path, index=False)
    print(f"Wrote {path}  shape={df.shape}", flush=True)

    meta = OUT / "dataset_metadata.txt"
    with meta.open("w") as fh:
        fh.write(f"name: {repo.metadata.name}\n")
        fh.write(f"uci_id: {repo.metadata.uci_id}\n")
        fh.write(f"url: {repo.metadata.repository_url}\n")
        fh.write(f"instances: {repo.metadata.num_instances}\n")
        fh.write(f"features: {repo.metadata.num_features}\n")
        fh.write(f"columns: {list(df.columns)}\n")
        fh.write("\n--- readmitted value counts ---\n")
        fh.write(str(df["readmitted"].value_counts()))
        fh.write("\n")
    print(f"Wrote {meta}", flush=True)

    print("\n--- readmitted value counts ---", flush=True)
    print(df["readmitted"].value_counts(), flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
