# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Stage 7 GATE: freeze the twin at the chosen settings and validate it.

The twin is the executable specification. If it is decode-safe and reproduces
the reference here, the encrypted build is a mechanical transcription of it and
should match to within encryption noise.

Checks performed
----------------
  1. External oracle: the hand-written weighted tally is diffed against
     scikit-learn's own decision_function on the same inputs. This turns an
     internal consistency check ("our twin agrees with our reference") into an
     external one against a widely-used BSD-licensed implementation.
  2. Decision rule: the twin must use the reference's exact rule.
  3. Twin vs reference on held-out patients: band agreement, and the clinical
     metrics that actually matter.
  4. Decode safety: the modulus budget must hold, predicted from the
     cleartext side before spending an encrypted run.
  5. Noise tolerance: how much encryption error the design absorbs. This
     becomes the objective pass criterion for Stage 8.
  6. Slot-level simulation of the single-patient rotate-and-sum path, so the
     C++ becomes a transcription of a program already verified in numpy.

Writes model/circuit_params.json, the single source of truth the encrypted
programs read, so the twin and the C++ cannot drift apart.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_recall_fscore_support, roc_auc_score

sys.path.insert(0, str(Path(__file__).resolve().parent))
from twin import (  # noqa: E402
    Twin, TwinConfig, band_staircase, cheb_levels, load_model, quantize,
    reference_band,
)

ROOT = Path(__file__).resolve().parent.parent
DATA, MODEL, REPORTS = ROOT / "data", ROOT / "model", ROOT / "reports"

# ---- the frozen design point ---------------------------------------------
STEEPNESS = 24
DEGREE = 191
SCALING_BITS = 45
FIRST_MOD = 60
RING_DIM = 65536          # mandatory for the target hardware
SLOTS = RING_DIM // 2
SECURITY = "HEStd_128_classic"
FEATURE_SLOT_STRIDE = 32  # next power of 2 >= 28 features, for the per-patient path

ok = True


def check(label: str, passed: bool, detail: str = "") -> None:
    global ok
    ok = ok and passed
    print(f"  [{'PASS' if passed else 'FAIL'}] {label}"
          + (f"   {detail}" if detail else ""))


def main() -> None:
    model = load_model()
    X = np.load(DATA / "test_features.npy")
    y = np.load(DATA / "test_labels.npy")
    w = np.asarray(model["weights"]); b = float(model["bias"])
    n_feat = len(w)

    levels = 1 + cheb_levels(DEGREE)
    depth = levels + 2
    cfg = TwinConfig(STEEPNESS, DEGREE, SCALING_BITS, depth)
    tw = Twin(model, cfg)

    print("=" * 72)
    print("STAGE 7 GATE: faithful twin vs reference")
    print("=" * 72)
    print(f"  features {n_feat}   held-out patients {len(X):,}")
    print(f"  steepness {STEEPNESS}, polynomial degree {DEGREE}")
    print(f"  levels used {levels}, multiplicative depth {depth}, "
          f"scaling {SCALING_BITS} bits, first modulus {FIRST_MOD} bits")
    print(f"  ring dimension {RING_DIM} ({SLOTS:,} patient slots), {SECURITY}")
    print(f"  approximation domain [{tw.lo:.4f}, {tw.hi:.4f}] "
          f"(from the provable score range, padded 2%)")

    # -- 1. external oracle -------------------------------------------------
    print("\n1. External oracle (scikit-learn)")
    sk = LogisticRegression()
    sk.coef_ = w.reshape(1, -1); sk.intercept_ = np.array([b])
    sk.classes_ = np.array([0, 1])
    d_sk = sk.decision_function(X)
    d_tw = X @ w + b
    check("weighted tally matches sklearn.decision_function",
          np.allclose(d_sk, d_tw, atol=1e-12),
          f"max diff {np.max(np.abs(d_sk - d_tw)):.2e}")

    # -- 2. decision rule ---------------------------------------------------
    print("\n2. Decision rule")
    ref = reference_band(X, model)
    manual = ((d_sk > model["threshold_moderate"]).astype(int)
              + (d_sk > model["threshold_high"]).astype(int))
    check("reference uses two threshold comparisons, not argmax",
          np.array_equal(ref, manual))

    # -- 3. twin vs reference ------------------------------------------------
    print("\n3. Twin vs reference on held-out patients")
    band = tw.band(X)
    agree = float((band == ref).mean())
    check("band agreement >= 99.9%", agree >= 0.999,
          f"{agree*100:.4f}%  ({int((band != ref).sum())} of {len(X):,} differ)")

    rp, rr, rf, _ = precision_recall_fscore_support(
        y, (ref == 2).astype(int), average="binary", zero_division=0)
    tp, tr_, tf, _ = precision_recall_fscore_support(
        y, (band == 2).astype(int), average="binary", zero_division=0)
    check("high-band precision preserved", abs(tp - rp) <= 1e-3,
          f"reference {rp:.4f} -> twin {tp:.4f}  (delta {tp-rp:+.5f})")
    check("high-band recall preserved", abs(tr_ - rr) <= 1e-3,
          f"reference {rr:.4f} -> twin {tr_:.4f}  (delta {tr_-rr:+.5f})")

    auc_ref = roc_auc_score(y, d_sk)
    auc_tw = roc_auc_score(y, tw.band_value(X))
    print(f"       ranking quality (AUC): reference {auc_ref:.4f}, "
          f"twin band value {auc_tw:.4f}")

    grid = np.linspace(tw.lo, tw.hi, 200_000)
    poly_err = float(np.max(np.abs(
        tw.poly(grid) - band_staircase(grid, tw.t_mod, tw.t_high, STEEPNESS))))

    # The range the band polynomial can legitimately produce for ANY admissible
    # input. The deployed client checks decrypted values against this: a run that
    # lost its level budget or hit a key mismatch returns values far outside it,
    # and would otherwise be rounded into a plausible-looking clinical band.
    # Patients near a threshold decrypt to fractional values, so this is a range
    # check rather than a "close to a whole number" check.
    band_lo = float(np.min(tw.poly(grid)))
    band_hi = float(np.max(tw.poly(grid)))
    print(f"       band polynomial output range over the provable domain: "
          f"[{band_lo:.4f}, {band_hi:.4f}]")
    check("polynomial tracks the staircase across the WHOLE provable range",
          poly_err < 1e-2, f"worst error {poly_err:.2e}")

    # -- 4. decode safety ----------------------------------------------------
    print("\n4. Decode safety (predicted before spending an encrypted run)")
    worst = float(np.max(np.abs(tw.band_value(X))))
    margin = tw.decode_margin(FIRST_MOD, worst)
    check("modulus budget holds", margin > 0,
          f"spare {margin:+.1f} bits (worst output magnitude {worst:.3f})")
    check("depth within the no-bootstrap ceiling (~25-30)", depth <= 25,
          f"depth {depth}")
    logQ = FIRST_MOD + depth * SCALING_BITS
    check("ring dimension adequate for this modulus at 128-bit security",
          RING_DIM == 65536, f"logQ ~= {logQ} bits -> needs N = 2^16")

    # -- 5. noise tolerance --------------------------------------------------
    print("\n5. Encryption-noise tolerance (the Stage 8 pass criterion)")
    val = tw.band_value(X)
    headroom = 0.5 - np.abs(val - np.rint(val))
    at_risk = {f"{e:.0e}": int((headroom < e).sum()) for e in (1e-7, 1e-5, 1e-4, 1e-3)}
    for e, n in at_risk.items():
        print(f"       noise {e:>8}: {n:>3} of {len(X):,} patients could change band")
    check("no patient at risk at the expected noise level (1e-5)",
          at_risk["1e-05"] == 0)
    tolerance = 1e-4
    print(f"       -> Stage 8 passes if measured |FHE - twin| < {tolerance:.0e} "
          f"AND band agreement is 100%")

    # -- 6. slot-level simulation of the per-patient path --------------------
    print("\n6. Slot-level simulation: single-patient rotate-and-sum path")
    # One patient's features occupy slots [0, n_feat); the server multiplies by a
    # plaintext weight vector, then folds the slots together by repeatedly
    # rotating and adding. Replaying that exact program with np.roll here means
    # the C++ is a transcription of something already proven correct.
    rng = np.random.default_rng(3)
    sample = X[rng.choice(len(X), 256, replace=False)]
    wpad = np.zeros(FEATURE_SLOT_STRIDE); wpad[:n_feat] = w
    sim = []
    for row in sample:
        slots = np.zeros(FEATURE_SLOT_STRIDE); slots[:n_feat] = row
        acc = slots * wpad
        r = 1
        while r < FEATURE_SLOT_STRIDE:          # rotate-and-sum, log2(32) = 5 steps
            acc = acc + np.roll(acc, -r)
            r *= 2
        sim.append(acc[0] + b)
    sim = np.asarray(sim)
    direct = sample @ w + b
    check("rotate-and-sum reproduces the batch tally",
          np.allclose(sim, direct, atol=1e-12),
          f"max diff {np.max(np.abs(sim - direct)):.2e}")
    check("rotation amounts are powers of two up to the stride",
          FEATURE_SLOT_STRIDE >= n_feat and (FEATURE_SLOT_STRIDE
                                             & (FEATURE_SLOT_STRIDE - 1)) == 0,
          f"stride {FEATURE_SLOT_STRIDE}, rotations "
          f"{[2**i for i in range(int(np.log2(FEATURE_SLOT_STRIDE)))]}")

    # -- boundary sizes ------------------------------------------------------
    ct = 2 * RING_DIM * (depth + 1) * 8
    out_ct = 2 * RING_DIM * (depth - levels + 1) * 8
    print("\n7. Predicted sizes at the trust boundary")
    print(f"       one fresh ciphertext            {ct/2**20:6.0f} MiB")
    print(f"       batch upload ({n_feat} columns)      {n_feat*ct/2**20:6.0f} MiB"
          f"   ({SLOTS:,} patients, {n_feat*ct/SLOTS/1024:.1f} KiB each)")
    print(f"       single-patient upload (1 ct)    {ct/2**20:6.0f} MiB")
    print(f"       result returned                 {out_ct/2**20:6.0f} MiB")

    # -- freeze --------------------------------------------------------------
    # tw.poly is already a Chebyshev series on [domain_lo, domain_hi], so export
    # its coefficients directly. Converting "to Chebyshev" would re-map them onto
    # numpy's default [-1, 1] domain, silently describing a different function.
    coeffs = tw.poly.coef

    # A stored coefficient array nothing currently reads is exactly the kind of
    # artifact that rots unnoticed, so prove it reproduces the polynomial before
    # writing it. Anyone consuming these (a reimplementation, an audit) gets an
    # array that has been checked.
    probe = np.linspace(tw.lo, tw.hi, 1001)
    rebuilt = np.polynomial.Chebyshev(coeffs, domain=[tw.lo, tw.hi])(probe)
    check("exported coefficients reproduce the band polynomial",
          bool(np.allclose(rebuilt, tw.poly(probe), rtol=0, atol=1e-9)),
          f"max deviation {np.max(np.abs(rebuilt - tw.poly(probe))):.2e}")

    (MODEL / "circuit_params.json").write_text(json.dumps({
        "_comment": "Single source of truth for the twin and the encrypted "
                    "programs. Generated by scripts/gate.py; do not hand-edit.",
        "feature_names": model["feature_names"],
        "n_features": n_feat,
        "weights": w.tolist(),
        "bias": b,
        "threshold_moderate": model["threshold_moderate"],
        "threshold_high": model["threshold_high"],
        "steepness": STEEPNESS,
        "degree": DEGREE,
        "domain_lo": tw.lo,
        "domain_hi": tw.hi,
        "chebyshev_coeffs": coeffs.tolist(),
        "chebyshev_coeff_domain": [tw.lo, tw.hi],
        "ring_dim": RING_DIM,
        "slots": SLOTS,
        "multiplicative_depth": depth,
        "levels_used": levels,
        "scaling_mod_size": SCALING_BITS,
        "first_mod_size": FIRST_MOD,
        "security_level": SECURITY,
        "scaling_technique": "FLEXIBLEAUTO",
        "feature_slot_stride": FEATURE_SLOT_STRIDE,
        "rotations_per_record_mode": [2 ** i for i in
                                      range(int(np.log2(FEATURE_SLOT_STRIDE)))],
        "noise_tolerance": tolerance,
        "band_value_min": band_lo,
        "band_value_max": band_hi,
        "twin_band_agreement": agree,
        "twin_high_precision": float(tp),
        "twin_high_recall": float(tr_),
        "reference_high_precision": float(rp),
        "reference_high_recall": float(rr),
        "max_polynomial_error": poly_err,
        "predicted_decode_margin_bits": margin,
    }, indent=2))

    print("\n" + "=" * 72)
    print(f"GATE: {'PASS: cleared to build the encrypted version' if ok else 'FAIL'}")
    print("=" * 72)
    print(f"Wrote {MODEL/'circuit_params.json'}")
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
