# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Run a command and record its peak memory use.

Peak resident memory of the server stage is the number every deployment-sizing
conversation asks for, and it cannot be inferred from ciphertext sizes: the
working set includes temporaries the size estimates do not cover.

Uses resource.getrusage, so it needs no extra packages and works where
/usr/bin/time is absent. ru_maxrss is bytes on macOS and kilobytes on Linux.

    run_with_rss.py <out.txt> <command> [args...]
"""

from __future__ import annotations

import resource
import subprocess
import sys

out_path, cmd = sys.argv[1], sys.argv[2:]

before = resource.getrusage(resource.RUSAGE_CHILDREN).ru_maxrss
rc = subprocess.call(cmd)
after = resource.getrusage(resource.RUSAGE_CHILDREN).ru_maxrss

raw = max(after, before)
mib = raw / (1024 * 1024) if sys.platform == "darwin" else raw / 1024

with open(out_path, "w") as fh:
    fh.write(f"{mib:.0f} MiB")

sys.exit(rc)
