# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Stages 5-6: sweep the circuit's two free knobs and pick the cheapest that works.

The knobs:
  * steepness  : how abrupt the band transition is. Steeper tracks the
                  reference's hard comparison more closely but is a harder shape
                  for a polynomial to follow.
  * degree     : how elaborate the approximating polynomial is. Higher is more
                  faithful but costs multiplicative depth, which costs ciphertext
                  size, memory and time.

The bar (the goal floor), set against the REFERENCE on held-out patients:
  * >= 99.9% of patients land in the same risk band
  * high-band precision and recall within 0.001 of the reference
  * the circuit is predicted to decode safely

Everything is measured on the faithful twin, which runs in seconds.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
from sklearn.metrics import precision_recall_fscore_support

sys.path.insert(0, str(Path(__file__).resolve().parent))
from twin import Twin, TwinConfig, cheb_levels, load_model, reference_band  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
REPORTS = ROOT / "reports"
REPORTS.mkdir(exist_ok=True)

AGREEMENT_FLOOR = 0.999
METRIC_TOL = 0.001

STEEPNESS = [8, 12, 16, 24, 32, 48]
DEGREES = [31, 63, 95, 127, 159, 191, 247]
SCALING_BITS = 45
FIRST_MOD = 60


def main() -> None:
    model = load_model()
    X = np.load(DATA / "test_features.npy")
    y = np.load(DATA / "test_labels.npy")
    ref = reference_band(X, model)

    rp, rr, _, _ = precision_recall_fscore_support(
        y, (ref == 2).astype(int), average="binary", zero_division=0)

    print(f"Reference on {len(X):,} held-out patients: "
          f"high-band precision {rp:.4f}, recall {rr:.4f}")
    print(f"Provable score range: [{model['score_min_provable']:.4f}, "
          f"{model['score_max_provable']:.4f}]\n")

    print(f"{'steep':>6} {'deg':>5} {'lvls':>5} {'depth':>6} {'agree%':>9} "
          f"{'flips':>7} {'maxerr':>9} {'prec_d':>8} {'rec_d':>8} {'decode':>8} {'':>5}")
    print("-" * 88)

    rows = []
    for k in STEEPNESS:
        for deg in DEGREES:
            levels = 1 + cheb_levels(deg)
            # One nominal spare level, plus one more: under FLEXIBLEAUTO the
            # naive per-operation count can undercount real consumption, so a
            # nominal spare of one can be an effective spare of zero.
            depth = levels + 2
            cfg = TwinConfig(steepness=k, degree=deg,
                             scaling_bits=SCALING_BITS, depth=depth)
            tw = Twin(model, cfg)

            band = tw.band(X)
            val = tw.band_value(X)
            agree = float((band == ref).mean())
            flips = int((band != ref).sum())

            # How far the polynomial strays from the staircase it approximates,
            # measured densely across the whole provable domain, not just at
            # the test points, since a deployed patient can sit anywhere in it.
            grid = np.linspace(tw.lo, tw.hi, 20000)
            from twin import band_staircase
            maxerr = float(np.max(np.abs(
                tw.poly(grid) - band_staircase(grid, tw.t_mod, tw.t_high, k))))

            p, r, _, _ = precision_recall_fscore_support(
                y, (band == 2).astype(int), average="binary", zero_division=0)

            worst = float(np.max(np.abs(val)))
            margin = tw.decode_margin(FIRST_MOD, worst)

            ok = (agree >= AGREEMENT_FLOOR
                  and abs(p - rp) <= METRIC_TOL
                  and abs(r - rr) <= METRIC_TOL
                  and margin > 0)
            rows.append(dict(steepness=k, degree=deg, levels=levels, depth=depth,
                             agreement=agree, flips=flips, max_poly_err=maxerr,
                             prec=float(p), rec=float(r),
                             prec_delta=float(p - rp), rec_delta=float(r - rr),
                             decode_margin=margin, passes=bool(ok)))
            print(f"{k:>6} {deg:>5} {levels:>5} {depth:>6} {agree*100:>8.4f}% "
                  f"{flips:>7} {maxerr:>9.2e} {p-rp:>+8.4f} {r-rr:>+8.4f} "
                  f"{margin:>+8.1f} {'PASS' if ok else '':>5}")

    passing = [r for r in rows if r["passes"]]
    print("\n" + "=" * 88)
    if not passing:
        print("NO PASSING POINT. Escalate per the Stage 3 ladder.")
        (REPORTS / "sweep.json").write_text(json.dumps(rows, indent=2))
        sys.exit(1)

    # Cheapest = fewest levels; break ties by fewest flips, then lowest degree.
    best = min(passing, key=lambda r: (r["levels"], r["flips"], r["degree"]))
    print("CHEAPEST PASSING POINT")
    print(f"  steepness {best['steepness']}, degree {best['degree']}")
    print(f"  levels used {best['levels']}, multiplicative depth {best['depth']}")
    print(f"  band agreement {best['agreement']*100:.4f}% "
          f"({best['flips']} of {len(X):,} patients differ)")
    print(f"  high-band precision delta {best['prec_delta']:+.5f}, "
          f"recall delta {best['rec_delta']:+.5f}")
    print(f"  worst polynomial error across the whole provable range "
          f"{best['max_poly_err']:.2e}")
    print(f"  predicted decode margin {best['decode_margin']:+.1f} bits")
    print("=" * 88)

    (REPORTS / "sweep.json").write_text(json.dumps(
        {"floor": {"agreement": AGREEMENT_FLOOR, "metric_tol": METRIC_TOL},
         "reference": {"high_precision": float(rp), "high_recall": float(rr)},
         "scaling_bits": SCALING_BITS, "first_mod": FIRST_MOD,
         "rows": rows, "chosen": best}, indent=2))
    print(f"\nWrote {REPORTS/'sweep.json'}")


if __name__ == "__main__":
    main()
