# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""The FAITHFUL TWIN: a plaintext model of the exact encrypted circuit.

Three versions of this application exist and must not be conflated:

  1. the REFERENCE  (scripts/build_reference.py): the ideal computation,
     true logistic regression, exact `score > threshold` comparisons.
  2. the TWIN       (this file)                 : the same algorithm reshaped
     into what encryption can actually do: the hard band comparison replaced by
     ONE polynomial, values quantised the way CKKS quantises them.
  3. the FHE PROGRAM (Stage 8)                  : the encrypted implementation,
     which should reproduce the twin to within encryption noise.

The twin is the executable specification. It runs in seconds, so parameters are
chosen against it rather than against hour-long encrypted runs.

The circuit it models
---------------------
    score = sum_j w_j * x_j + b            cipher x plaintext, 1 level
    band  = P(score)                       one Chebyshev polynomial, ~6 levels

P approximates the two-step staircase

    f(s) = sigmoid(k*(s - t_mod)) + sigmoid(k*(s - t_high))

over the PROVABLE score interval. One polynomial evaluation produces the band
directly, rather than two separate threshold comparisons, at the same depth, half the
work, one output ciphertext.

The client rounds the decrypted value to the nearest of {0, 1, 2}.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np
from numpy.polynomial import chebyshev as C

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
MODEL = ROOT / "model"


# --------------------------------------------------------------------------
# CKKS-shaped quantisation
# --------------------------------------------------------------------------
def quantize(x: np.ndarray, scaling_bits: int) -> np.ndarray:
    """Round to the CKKS scaling grid (delta = 2^scaling_bits).

    At the scaling sizes used here this is a ~1e-14 relative perturbation, far
    below the polynomial approximation error. It is modelled anyway so the twin
    is a true picture of the circuit rather than an idealisation of it.
    """
    delta = float(2 ** scaling_bits)
    return np.rint(x * delta) / delta


# --------------------------------------------------------------------------
# The band staircase and its Chebyshev interpolant
# --------------------------------------------------------------------------
def band_staircase(s: np.ndarray, t_mod: float, t_high: float, k: float) -> np.ndarray:
    """Smooth two-step staircase: ~0 below t_mod, ~1 between, ~2 above t_high.

    `k` sets how abruptly each step rises. Steeper is a more faithful stand-in
    for the reference's hard comparison, but a harder shape for a polynomial to
    follow, so it costs approximation degree.
    """
    return 1.0 / (1.0 + np.exp(-k * (s - t_mod))) + 1.0 / (
        1.0 + np.exp(-k * (s - t_high))
    )


def chebyshev_interpolant(func, lo: float, hi: float, degree: int) -> C.Chebyshev:
    """Degree-`degree` Chebyshev interpolant of `func` on [lo, hi].

    Matches what OpenFHE's EvalChebyshevFunction builds, so the twin evaluates
    the same polynomial the server will evaluate.
    """
    return C.Chebyshev.interpolate(func, degree, domain=[lo, hi])


def cheb_levels(degree: int) -> int:
    """Multiplicative levels charged for a Chebyshev evaluation of this degree."""
    return int(np.ceil(np.log2(degree + 1))) + 1


# --------------------------------------------------------------------------
# The model, as the twin sees it
# --------------------------------------------------------------------------
@dataclass
class TwinConfig:
    steepness: float      # k in the staircase
    degree: int           # Chebyshev degree
    scaling_bits: int     # CKKS scaling modulus size, bits per level
    depth: int            # multiplicative depth of the circuit


class Twin:
    def __init__(self, model: dict, cfg: TwinConfig):
        self.w = np.asarray(model["weights"], dtype=np.float64)
        self.b = float(model["bias"])
        self.t_mod = float(model["threshold_moderate"])
        self.t_high = float(model["threshold_high"])
        self.cfg = cfg

        # The approximation domain comes from the PROVABLE score range, not from
        # observed data. Because every feature is clipped into [0,1] before
        # encryption, the score cannot escape this interval for ANY admissible
        # input, so the polynomial is never evaluated outside its fit
        # region, so one record cannot spoil a batched encrypted run.
        self.lo = float(model["score_min_provable"])
        self.hi = float(model["score_max_provable"])
        # A small margin absorbs encryption noise near the ends.
        pad = 0.02 * (self.hi - self.lo)
        self.lo -= pad
        self.hi += pad

        self.poly = chebyshev_interpolant(
            lambda s: band_staircase(s, self.t_mod, self.t_high, cfg.steepness),
            self.lo, self.hi, cfg.degree,
        )

    # -- the circuit, step by step -----------------------------------------
    def score(self, X: np.ndarray) -> np.ndarray:
        """Weighted tally. One cipher x plaintext multiply-accumulate."""
        w = quantize(self.w, self.cfg.scaling_bits)
        s = X @ w + self.b
        return quantize(s, self.cfg.scaling_bits)

    def band_value(self, X: np.ndarray) -> np.ndarray:
        """Raw polynomial output, before the client rounds it."""
        return quantize(self.poly(self.score(X)), self.cfg.scaling_bits)

    def band(self, X: np.ndarray) -> np.ndarray:
        """The decrypted decision: nearest of {0, 1, 2}."""
        return np.clip(np.rint(self.band_value(X)), 0, 2).astype(int)

    # -- accounting ---------------------------------------------------------
    @property
    def levels_used(self) -> int:
        return 1 + cheb_levels(self.cfg.degree)

    def decode_margin(self, first_mod: int, worst_operand: float,
                      noise_margin: int = 10) -> float:
        """Spare modulus budget at the end of the circuit, in bits.

        Positive means the encrypted result is predicted to decode; negative
        predicts an 'approximation error too high' failure. Checking this on the
        cleartext side reserves the expensive encrypted run for designs already
        believed safe.
        """
        spare = self.cfg.depth - self.levels_used
        left = first_mod + spare * self.cfg.scaling_bits
        right = self.cfg.scaling_bits + np.log2(max(worst_operand, 1.0)) + noise_margin
        return float(left - right)


# --------------------------------------------------------------------------
def load_model() -> dict:
    return json.loads((MODEL / "model.json").read_text())


def reference_band(X: np.ndarray, model: dict) -> np.ndarray:
    """The reference's exact decision rule, for comparison."""
    w = np.asarray(model["weights"], dtype=np.float64)
    s = X @ w + float(model["bias"])
    return ((s > model["threshold_moderate"]).astype(int)
            + (s > model["threshold_high"]).astype(int))
