# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""Stress-test the shortlisted circuit settings before committing to one.

Three checks the headline sweep does not make:

  1. Does the agreement hold across the whole cohort, not just the held-out
     split? A setting that is perfect on one sample and not the other is fitting
     the sample.
  2. How much encryption noise can the design absorb before any patient's band
     changes? This becomes the objective pass criterion for the encrypted run:
     measured error below the recorded tolerance, rather than an arbitrary
     threshold.
  3. Does agreement survive the worst case the input contract allows: patients
     placed adversarially at the band boundaries, not just the ones the data
     happened to contain?
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_reference import (  # noqa: E402
    FEATURE_NAMES, build_raw_frame, cohort, scale_box,
)
from twin import Twin, TwinConfig, load_model, reference_band  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
REPORTS = ROOT / "reports"

CANDIDATES = [
    ("degree 127, 9 levels ", 24, 127),
    ("degree 159, 10 levels", 24, 159),
    ("degree 191, 10 levels", 24, 191),
]
SCALING_BITS = 45


def full_cohort() -> np.ndarray:
    """Every encounter the reference model was built on, held-out and training.

    Must match build_reference's cohort exactly. It keeps repeat admissions, so
    the frequent admitters that dominate the deployed population are represented
    here too.
    """
    df = cohort(pd.read_csv(DATA / "raw_encounters.csv", low_memory=False))
    return scale_box(build_raw_frame(df).to_numpy(dtype=np.float64))


def adversarial_scores(model: dict, n: int = 200_000) -> np.ndarray:
    """Scores concentrated where the decision is hardest: at the band edges.

    Real patients cluster away from the thresholds, so a test set flatters the
    design. This samples densely across the boundaries instead.
    """
    rng = np.random.default_rng(7)
    lo = model["score_min_provable"]
    hi = model["score_max_provable"]
    edges = np.concatenate([
        model["threshold_moderate"] + rng.normal(0, 0.02, n // 2),
        model["threshold_high"] + rng.normal(0, 0.02, n // 2),
    ])
    return np.clip(edges, lo, hi)


def main() -> None:
    model = load_model()
    Xte = np.load(DATA / "test_features.npy")
    Xall = full_cohort()
    print(f"Held-out patients : {len(Xte):,}")
    print(f"Full cohort       : {len(Xall):,}")

    ref_te = reference_band(Xte, model)
    ref_all = reference_band(Xall, model)

    t_mod = model["threshold_moderate"]
    t_high = model["threshold_high"]
    adv_s = adversarial_scores(model)
    ref_adv = (adv_s > t_mod).astype(int) + (adv_s > t_high).astype(int)

    results = []
    for label, k, deg in CANDIDATES:
        cfg = TwinConfig(steepness=k, degree=deg, scaling_bits=SCALING_BITS,
                         depth=1 + int(np.ceil(np.log2(deg + 1))) + 1 + 2)
        tw = Twin(model, cfg)

        f_te = int((tw.band(Xte) != ref_te).sum())
        f_all = int((tw.band(Xall) != ref_all).sum())

        # Adversarial: evaluate the polynomial directly on boundary-dense scores.
        adv_band = np.clip(np.rint(tw.poly(adv_s)), 0, 2).astype(int)
        f_adv = int((adv_band != ref_adv).sum())

        # --- noise tolerance --------------------------------------------------
        # Each patient's band changes if the decrypted value drifts further than
        # its distance to the nearest rounding boundary. Across 70,000 patients
        # SOMEONE always sits essentially on a boundary, which follows from
        # banding a continuous score, so a single worst-case
        # minimum carries no information. The figure below is how many patients a
        # given amount of noise puts at risk.
        val_all = tw.band_value(Xall)
        headroom = 0.5 - np.abs(val_all - np.rint(val_all))   # per-patient slack

        at_risk = {}
        for eps in (1e-9, 1e-7, 1e-5, 1e-4, 1e-3):
            at_risk[f"{eps:.0e}"] = int((headroom < eps).sum())

        # Empirical confirmation: inject noise at each level and count real flips.
        rng = np.random.default_rng(11)
        observed = {}
        for eps in (1e-5, 1e-4, 1e-3):
            noisy = val_all + rng.uniform(-eps, eps, len(val_all))
            nb = np.clip(np.rint(noisy), 0, 2).astype(int)
            observed[f"{eps:.0e}"] = int((nb != tw.band(Xall)).sum())

        pcts = {f"p{p}": float(np.percentile(headroom, p)) for p in (0, 1, 10, 50)}

        levels = 1 + int(np.ceil(np.log2(deg + 1))) + 1
        row = dict(label=label, steepness=k, degree=deg, levels=levels,
                   depth=cfg.depth,
                   flips_heldout=f_te, n_heldout=len(Xte),
                   flips_cohort=f_all, n_cohort=len(Xall),
                   flips_adversarial=f_adv, n_adversarial=len(adv_s),
                   headroom_percentiles=pcts,
                   patients_at_risk_by_noise=at_risk,
                   observed_flips_by_noise=observed)
        results.append(row)

        print(f"\n--- {label}: steepness {k}, degree {deg} "
              f"({levels} levels, depth {cfg.depth}) ---")
        print(f"  band mismatches, held-out : {f_te:>6,} / {len(Xte):,}"
              f"   ({f_te/len(Xte)*100:.4f}%)")
        print(f"  band mismatches, cohort   : {f_all:>6,} / {len(Xall):,}"
              f"   ({f_all/len(Xall)*100:.4f}%)")
        print(f"  band mismatches, boundary-dense adversarial : "
              f"{f_adv:>6,} / {len(adv_s):,}   ({f_adv/len(adv_s)*100:.4f}%)")
        print(f"  patients whose band could change at a given encryption noise:")
        for eps, n in at_risk.items():
            obs = observed.get(eps)
            obs_s = f"   (injected: {obs} actually changed)" if obs is not None else ""
            print(f"     noise {eps:>8}: {n:>4} of {len(Xall):,} at risk{obs_s}")

    (REPORTS / "candidate_validation.json").write_text(json.dumps(results, indent=2))
    print(f"\nWrote {REPORTS/'candidate_validation.json'}")


if __name__ == "__main__":
    main()
