#!/usr/bin/env python3
# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""The HOSPITAL's process. Generates keys, encrypts, asks the vendor, decrypts.

Everything secret stays here. The only things that go over the network are the
public and evaluation keys (once, at setup) and ciphertext.

    client_app.py <client_home> --url http://host:8710 [--mode per_record]
                  [--record 0] [--n 1]
"""

from __future__ import annotations

import argparse
import csv
import io
import pathlib
import subprocess
import sys
import time
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
BUILD = ROOT / "build"
BAND = ["low", "moderate", "high"]


def log(msg: str) -> None:
    print(f"[hospital] {msg}", flush=True)


def post(url: str, name: str, blob: bytes) -> bytes:
    req = urllib.request.Request(f"{url}/input/{name}", data=blob, method="POST")
    req.add_header("Content-Type", "application/octet-stream")
    with urllib.request.urlopen(req) as r:
        return r.read()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("home")
    ap.add_argument("--url", default="http://127.0.0.1:8710")
    ap.add_argument("--mode", default="per_record", choices=["per_record", "batch"])
    ap.add_argument("--record", type=int, default=0)
    ap.add_argument("--n", type=int, default=1)
    a = ap.parse_args()

    home = pathlib.Path(a.home).resolve()

    log(f"encrypting patient data (shape: {a.mode})")
    subprocess.run([str(BUILD / "rescrubbed_encrypt"), str(home),
                    str(ROOT / "data" / "test_records.csv"),
                    str(ROOT / "data" / "feature_bounds.csv"),
                    "--mode", a.mode, "--n", str(a.n),
                    "--offset", str(a.record)], check=True)

    cts = sorted(home.glob("ct_x*.bin"))
    total = 0
    t0 = time.time()
    for p in cts:
        blob = p.read_bytes()
        total += len(blob)
        post(a.url, p.name, blob)
    log(f"sent {total:,} bytes of ciphertext to the vendor "
        f"({total/2**20:.1f} MiB, {len(cts)} ciphertext(s))")
    log("the decryption key stayed here and was never transmitted")

    result = post(a.url, "ct_go.bin", (home / "meta.txt").read_bytes())
    (home / "ct_result.bin").write_bytes(result)
    log(f"received {len(result):,} bytes back, still encrypted "
        f"({time.time()-t0:.2f}s round trip)")

    log("decrypting locally")
    out = subprocess.run([str(BUILD / "rescrubbed_decrypt"), str(home)],
                         capture_output=True, text=True, check=True).stdout
    # Read by column NAME, not position: the deployed decrypt emits
    # index,band,band_name and only adds `value` under --raw, which a client
    # never passes. Positional parsing silently mis-reads one of those layouts.
    rows = list(csv.DictReader(io.StringIO(out)))

    print()
    print("  " + "=" * 56)
    if a.mode == "per_record":
        print(f"  RISK BAND for the patient at test-set row {a.record}: "
              f"{rows[0]['band_name'].upper()}")
    else:
        counts = {b: 0 for b in BAND}
        for r in rows:
            counts[r["band_name"]] += 1
        print(f"  RISK BANDS for {len(rows):,} patients:")
        for b in BAND:
            print(f"     {b:<10} {counts[b]:>7,}")
    print("  " + "=" * 56)
    print("  The vendor computed this without ever being able to read the")
    print("  patient data, the score, or the band it returned.")
    print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
