#!/usr/bin/env bash
# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
#
# Two processes, two homes, one network hop. Nothing but ciphertext crosses it.
#
# The client process holds the patient data and the only decryption key. The
# server process holds the model and evaluation keys. They exchange nothing but
# ciphertext. The server home is safe to copy to an untrusted host as is; point
# the client at it with DEMO_URL.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEMO="$ROOT/demo"
CLIENT="$DEMO/client_home"; SERVER="$DEMO/server_home"
PORT="${DEMO_PORT:-8710}"
URL="${DEMO_URL:-http://127.0.0.1:$PORT}"
APP_MODE="${APP_MODE:-per_record}"      # the interactive at-discharge shape
RECORD="${RECORD:-0}"
NREC="${NREC:-1}"
PY="$ROOT/.venv/bin/python"; [ -x "$PY" ] || PY=python3

rm -rf "$CLIENT" "$SERVER"; mkdir -p "$CLIENT" "$SERVER"

echo "=============================================================================="
echo " Two-process deployment: hospital <-> scoring vendor"
echo "=============================================================================="

# ── the hospital generates every key, on its own host ────────────────────────
# It receives circuit.txt (public parameters) and never model.txt (the weights).
cp "$ROOT/model/circuit.txt" "$CLIENT/"
"$ROOT/build/readmit_keygen" "$CLIENT" "$APP_MODE"

# ── provision the vendor's host: no secret key, no patient data ──────────────
cp "$CLIENT/cc.bin" "$CLIENT/pk.bin" "$CLIENT/mk.bin" "$CLIENT/rk.bin" "$SERVER/"
cp "$ROOT/model/model.txt" "$ROOT/model/circuit.txt" "$SERVER/"

echo
echo "-- what each host holds ------------------------------------------------------"
echo "   hospital ($CLIENT):"
ls "$CLIENT" | sed 's/^/     /'
echo "   vendor   ($SERVER):"
ls "$SERVER" | sed 's/^/     /'
[ ! -f "$SERVER/sk.bin" ] || { echo "[FATAL] sk.bin present on the vendor host"; exit 1; }
# Glob, not the single per-record filename: batch mode writes ct_x_f0..f27, so
# checking only ct_x.bin would assert nothing at all under APP_MODE=batch.
if compgen -G "$SERVER/ct_x*.bin" >/dev/null; then
  echo "[FATAL] patient ciphertext present on the vendor host before any request"; exit 1
fi
[ ! -f "$SERVER/../client_home/model.txt" ] || { echo "[FATAL] weights on the client host"; exit 1; }
echo "   asserted: no sk.bin and no patient data on the vendor host  [OK]"
echo "   asserted: no model weights on the hospital host             [OK]"

# ── plant a secret key and confirm the server refuses to start ───────────────
# The wait below is bounded. Without a bound, a regressed guard would let the
# process reach serve_forever() and this check would hang instead of reporting.
cp "$CLIENT/sk.bin" "$SERVER/sk.bin"
NEG_LOG="$DEMO/.neg_test.log"
set +e
$PY "$DEMO/server_app.py" "$SERVER" --port "$PORT" >"$NEG_LOG" 2>&1 &
NEG_PID=$!
# Bounded wait, written with shell built-ins: `timeout` is not present on macOS
# by default, and shelling out to something absent would itself look like the
# guard failing (exit 127).
NEG_RC=""
for _ in $(seq 1 40); do
  kill -0 "$NEG_PID" 2>/dev/null || { wait "$NEG_PID"; NEG_RC=$?; break; }
  sleep 0.5
done
if [ -z "$NEG_RC" ]; then
  kill "$NEG_PID" 2>/dev/null; wait "$NEG_PID" 2>/dev/null
  NEG_RC=124
fi
set -e
NEG=$(cat "$NEG_LOG"); rm -f "$NEG_LOG"
rm -f "$SERVER/sk.bin"
if [ "$NEG_RC" -eq 124 ]; then
  echo "[FATAL] the vendor process kept running with a decryption key present"; exit 1
fi
if [ "$NEG_RC" -ne 2 ]; then
  echo "[FATAL] expected the key guard (exit 2), got exit $NEG_RC:"; echo "$NEG" | head -3; exit 1
fi
echo "   negative test: vendor process refused a planted key (exit 2)  [OK]"
echo

# ── start the vendor process ─────────────────────────────────────────────────
# --flag=--cpu, not --flag --cpu: argparse would read a bare "--cpu" as a flag.
$PY "$DEMO/server_app.py" "$SERVER" --port "$PORT" --flag=--cpu &
SRV_PID=$!
trap 'kill $SRV_PID 2>/dev/null || true' EXIT

for _ in $(seq 1 50); do
  curl -fsS "$URL" >/dev/null 2>&1 && break
  sleep 0.2
done

# ── the hospital asks for a score ────────────────────────────────────────────
$PY "$DEMO/client_app.py" "$CLIENT" --url "$URL" \
    --mode "$APP_MODE" --record "$RECORD" --n "$NREC"

kill $SRV_PID 2>/dev/null || true
wait $SRV_PID 2>/dev/null || true

echo "To run the vendor half on a different machine: copy demo/server_home there,"
echo "start server_app.py on it, and set DEMO_URL to its address. Nothing in that"
echo "directory can decrypt anything."
