#!/usr/bin/env python3
# Generated by the Niobium FHE Application Design AI Assistant (FHEanna).
"""The VENDOR's process. Stands up an HTTP endpoint over the scoring binary.

This is the half that runs on infrastructure the hospital does not trust. Its
home directory holds the model and the evaluation keys and nothing else: no
decryption key, no patient data, so it is safe to copy to a rented machine as
is.

It logs byte counts only, never values, because values are all it ever has.

    server_app.py <server_home> [--port 8710] [--flag --cpu]
"""

from __future__ import annotations

import argparse
import http.server
import pathlib
import subprocess
import sys
import time

ROOT = pathlib.Path(__file__).resolve().parent.parent
BIN = ROOT / "build" / "readmit_server"


def log(msg: str) -> None:
    print(f"[vendor] {msg}", flush=True)


class Handler(http.server.BaseHTTPRequestHandler):
    home: pathlib.Path
    flag: str

    def log_message(self, *_args):        # silence the default access log
        pass

    def do_GET(self):                     # simple liveness probe
        self.send_response(200)
        self.end_headers()
        self.wfile.write(b"ready")

    def do_POST(self):
        # Path carries the input filename, e.g. /input/ct_x.bin
        name = self.path.rsplit("/", 1)[-1]
        if not name.startswith("ct_") or not name.endswith(".bin"):
            self.send_error(400, "bad input name")
            return

        n = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(n)

        if name == "ct_go.bin":
            # The client has finished uploading; run the circuit.
            meta = body.decode()
            (self.home / "meta.txt").write_text(meta)
            log(f"request complete; running the scoring circuit ({meta.strip()!r})")
            t0 = time.time()
            r = subprocess.run([str(BIN), str(self.home)] + self.flag.split(),
                               capture_output=True, text=True)
            for line in (r.stdout + r.stderr).splitlines():
                log(f"  {line}")
            if r.returncode != 0:
                self.send_error(500, "circuit failed")
                return
            out = (self.home / "ct_result.bin").read_bytes()
            log(f"returning {len(out):,} bytes, still encrypted "
                f"({time.time()-t0:.2f}s), no plaintext was ever available here")
            self.send_response(200)
            self.send_header("Content-Type", "application/octet-stream")
            self.send_header("Content-Length", str(len(out)))
            self.end_headers()
            self.wfile.write(out)
            return

        (self.home / name).write_bytes(body)
        log(f"received {len(body):,} bytes of ciphertext as {name}, unreadable here")
        self.send_response(204)
        self.end_headers()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("home")
    ap.add_argument("--port", type=int, default=8710)
    ap.add_argument("--flag", default="--cpu")
    # Loopback by default so a casual run does not expose a scoring endpoint on
    # the network. The two-host deployment described in the README needs
    # --bind 0.0.0.0 on the vendor machine; without it the client's connection
    # from another host is simply refused.
    ap.add_argument("--bind", default="127.0.0.1",
                    help="address to listen on (use 0.0.0.0 for a remote client)")
    a = ap.parse_args()

    home = pathlib.Path(a.home).resolve()

    # The same guard the binary enforces, checked before we even open a socket.
    if (home / "sk.bin").exists():
        log("FATAL: a secret key is present in the server home. Refusing to start.")
        return 2
    for required in ("cc.bin", "pk.bin", "mk.bin", "rk.bin", "model.txt"):
        if not (home / required).exists():
            log(f"FATAL: {required} missing from the server home")
            return 2

    Handler.home = home
    Handler.flag = a.flag
    srv = http.server.ThreadingHTTPServer((a.bind, a.port), Handler)
    log(f"listening on {a.bind}:{a.port}; home={home}")
    log("holds: model + evaluation keys.  does NOT hold: decryption key, patient data")
    try:
        srv.serve_forever()
    except KeyboardInterrupt:
        pass
    return 0


if __name__ == "__main__":
    sys.exit(main())
